package com.work.mapper;

import com.work.entity.TbBlReply;
import com.work.entity.TbBlReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBlReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int countByExample(TbBlReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int deleteByExample(TbBlReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int deleteByPrimaryKey(String fdReplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int insert(TbBlReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int insertSelective(TbBlReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    List<TbBlReply> selectByExample(TbBlReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    TbBlReply selectByPrimaryKey(String fdReplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbBlReply record, @Param("example") TbBlReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int updateByExample(@Param("record") TbBlReply record, @Param("example") TbBlReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int updateByPrimaryKeySelective(TbBlReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_REPLY
     *
     * @mbggenerated Fri Mar 31 14:06:44 CST 2017
     */
    int updateByPrimaryKey(TbBlReply record);
}