package com.work.mapper;

import com.work.entity.TbBlSupport;
import com.work.entity.TbBlSupportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBlSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int countByExample(TbBlSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int deleteByExample(TbBlSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int deleteByPrimaryKey(String fdSupportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int insert(TbBlSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int insertSelective(TbBlSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    List<TbBlSupport> selectByExample(TbBlSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    TbBlSupport selectByPrimaryKey(String fdSupportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbBlSupport record, @Param("example") TbBlSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int updateByExample(@Param("record") TbBlSupport record, @Param("example") TbBlSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int updateByPrimaryKeySelective(TbBlSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    int updateByPrimaryKey(TbBlSupport record);
}