package com.work.mapper;

import com.work.entity.TbBlBlogFollow;
import com.work.entity.TbBlBlogFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBlBlogFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int countByExample(TbBlBlogFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int deleteByExample(TbBlBlogFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int insert(TbBlBlogFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int insertSelective(TbBlBlogFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    List<TbBlBlogFollow> selectByExample(TbBlBlogFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    TbBlBlogFollow selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbBlBlogFollow record, @Param("example") TbBlBlogFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int updateByExample(@Param("record") TbBlBlogFollow record, @Param("example") TbBlBlogFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int updateByPrimaryKeySelective(TbBlBlogFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG_FOLLOW
     *
     * @mbggenerated Fri Apr 07 16:30:31 CST 2017
     */
    int updateByPrimaryKey(TbBlBlogFollow record);
}