package com.work.mapper;

import com.work.entity.TbPepmgmLeader;
import com.work.entity.TbPepmgmLeaderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbPepmgmLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int countByExample(TbPepmgmLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int deleteByExample(TbPepmgmLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int insert(TbPepmgmLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int insertSelective(TbPepmgmLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    List<TbPepmgmLeader> selectByExample(TbPepmgmLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbPepmgmLeader record, @Param("example") TbPepmgmLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PEPMGM_LEADER
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    int updateByExample(@Param("record") TbPepmgmLeader record, @Param("example") TbPepmgmLeaderExample example);
}