package com.work.mapper;

import com.work.entity.TbSugDetail;
import com.work.entity.TbSugDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbSugDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int countByExample(TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int deleteByExample(TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int insert(TbSugDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int insertSelective(TbSugDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    List<TbSugDetail> selectByExampleWithBLOBs(TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    List<TbSugDetail> selectByExample(TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbSugDetail record, @Param("example") TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TbSugDetail record, @Param("example") TbSugDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SUG_DETAIL
     *
     * @mbggenerated Tue Aug 28 10:46:46 CST 2018
     */
    int updateByExample(@Param("record") TbSugDetail record, @Param("example") TbSugDetailExample example);
}