package com.work.mapper.dating;

import com.work.entity.dating.TBUserActivityComment;
import com.work.entity.dating.TBUserActivityCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBUserActivityCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int countByExample(TBUserActivityCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int deleteByExample(TBUserActivityCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int insert(TBUserActivityComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int insertSelective(TBUserActivityComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    List<TBUserActivityComment> selectByExample(TBUserActivityCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    TBUserActivityComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBUserActivityComment record, @Param("example") TBUserActivityCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int updateByExample(@Param("record") TBUserActivityComment record, @Param("example") TBUserActivityCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int updateByPrimaryKeySelective(TBUserActivityComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_ACTIVITY_COMMENT
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    int updateByPrimaryKey(TBUserActivityComment record);
}