package com.work.mapper.dating;

import com.work.entity.dating.TBUserRelationIntermediay;
import com.work.entity.dating.TBUserRelationIntermediayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBUserRelationIntermediayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int countByExample(TBUserRelationIntermediayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int deleteByExample(TBUserRelationIntermediayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int insert(TBUserRelationIntermediay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int insertSelective(TBUserRelationIntermediay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    List<TBUserRelationIntermediay> selectByExample(TBUserRelationIntermediayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    TBUserRelationIntermediay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBUserRelationIntermediay record, @Param("example") TBUserRelationIntermediayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int updateByExample(@Param("record") TBUserRelationIntermediay record, @Param("example") TBUserRelationIntermediayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int updateByPrimaryKeySelective(TBUserRelationIntermediay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_INTERMEDIARY
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    int updateByPrimaryKey(TBUserRelationIntermediay record);
}