package com.work.mapper.dating;

import com.work.entity.dating.TbUserMarryStandard;
import com.work.entity.dating.TbUserMarryStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserMarryStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int countByExample(TbUserMarryStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int deleteByExample(TbUserMarryStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int insert(TbUserMarryStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int insertSelective(TbUserMarryStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    List<TbUserMarryStandard> selectByExample(TbUserMarryStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    TbUserMarryStandard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbUserMarryStandard record, @Param("example") TbUserMarryStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int updateByExample(@Param("record") TbUserMarryStandard record, @Param("example") TbUserMarryStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int updateByPrimaryKeySelective(TbUserMarryStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_MARRY_STANDARD
     *
     * @mbggenerated Tue May 02 13:40:43 CST 2017
     */
    int updateByPrimaryKey(TbUserMarryStandard record);
}