package com.work.mapper.dating;

import com.work.entity.dating.TBUserDatingInfo;
import com.work.entity.dating.TBUserDatingInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBUserDatingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int countByExample(TBUserDatingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int deleteByExample(TBUserDatingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int insert(TBUserDatingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int insertSelective(TBUserDatingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    List<TBUserDatingInfo> selectByExample(TBUserDatingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    TBUserDatingInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBUserDatingInfo record, @Param("example") TBUserDatingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int updateByExample(@Param("record") TBUserDatingInfo record, @Param("example") TBUserDatingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int updateByPrimaryKeySelective(TBUserDatingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_DATING_INFO
     *
     * @mbggenerated Thu May 04 12:14:45 CST 2017
     */
    int updateByPrimaryKey(TBUserDatingInfo record);
}