package com.work.mapper.dating;

import com.work.entity.dating.TBUserIntermediaryRecommend;
import com.work.entity.dating.TBUserIntermediaryRecommendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBUserIntermediaryRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int countByExample(TBUserIntermediaryRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int deleteByExample(TBUserIntermediaryRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int insert(TBUserIntermediaryRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int insertSelective(TBUserIntermediaryRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    List<TBUserIntermediaryRecommend> selectByExample(TBUserIntermediaryRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    TBUserIntermediaryRecommend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBUserIntermediaryRecommend record, @Param("example") TBUserIntermediaryRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int updateByExample(@Param("record") TBUserIntermediaryRecommend record, @Param("example") TBUserIntermediaryRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int updateByPrimaryKeySelective(TBUserIntermediaryRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_INTERMEDIARY_RECOMMEND
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    int updateByPrimaryKey(TBUserIntermediaryRecommend record);
}