package com.work.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TbAppDailyNewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public TbAppDailyNewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFdNewsIdIsNull() {
            addCriterion("FD_NEWS_ID is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdIsNotNull() {
            addCriterion("FD_NEWS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdEqualTo(String value) {
            addCriterion("FD_NEWS_ID =", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdNotEqualTo(String value) {
            addCriterion("FD_NEWS_ID <>", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdGreaterThan(String value) {
            addCriterion("FD_NEWS_ID >", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdGreaterThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_ID >=", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdLessThan(String value) {
            addCriterion("FD_NEWS_ID <", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdLessThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_ID <=", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdLike(String value) {
            addCriterion("FD_NEWS_ID like", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdNotLike(String value) {
            addCriterion("FD_NEWS_ID not like", value, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdIn(List<String> values) {
            addCriterion("FD_NEWS_ID in", values, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdNotIn(List<String> values) {
            addCriterion("FD_NEWS_ID not in", values, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdBetween(String value1, String value2) {
            addCriterion("FD_NEWS_ID between", value1, value2, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsIdNotBetween(String value1, String value2) {
            addCriterion("FD_NEWS_ID not between", value1, value2, "fdNewsId");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypIsNull() {
            addCriterion("FD_NEWS_TYP is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypIsNotNull() {
            addCriterion("FD_NEWS_TYP is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypEqualTo(String value) {
            addCriterion("FD_NEWS_TYP =", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypNotEqualTo(String value) {
            addCriterion("FD_NEWS_TYP <>", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypGreaterThan(String value) {
            addCriterion("FD_NEWS_TYP >", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypGreaterThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_TYP >=", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypLessThan(String value) {
            addCriterion("FD_NEWS_TYP <", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypLessThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_TYP <=", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypLike(String value) {
            addCriterion("FD_NEWS_TYP like", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypNotLike(String value) {
            addCriterion("FD_NEWS_TYP not like", value, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypIn(List<String> values) {
            addCriterion("FD_NEWS_TYP in", values, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypNotIn(List<String> values) {
            addCriterion("FD_NEWS_TYP not in", values, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypBetween(String value1, String value2) {
            addCriterion("FD_NEWS_TYP between", value1, value2, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsTypNotBetween(String value1, String value2) {
            addCriterion("FD_NEWS_TYP not between", value1, value2, "fdNewsTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconIsNull() {
            addCriterion("FD_NEWS_ICON is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconIsNotNull() {
            addCriterion("FD_NEWS_ICON is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconEqualTo(String value) {
            addCriterion("FD_NEWS_ICON =", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconNotEqualTo(String value) {
            addCriterion("FD_NEWS_ICON <>", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconGreaterThan(String value) {
            addCriterion("FD_NEWS_ICON >", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconGreaterThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_ICON >=", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconLessThan(String value) {
            addCriterion("FD_NEWS_ICON <", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconLessThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_ICON <=", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconLike(String value) {
            addCriterion("FD_NEWS_ICON like", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconNotLike(String value) {
            addCriterion("FD_NEWS_ICON not like", value, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconIn(List<String> values) {
            addCriterion("FD_NEWS_ICON in", values, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconNotIn(List<String> values) {
            addCriterion("FD_NEWS_ICON not in", values, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconBetween(String value1, String value2) {
            addCriterion("FD_NEWS_ICON between", value1, value2, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsIconNotBetween(String value1, String value2) {
            addCriterion("FD_NEWS_ICON not between", value1, value2, "fdNewsIcon");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerIsNull() {
            addCriterion("FD_NEWS_BANNER is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerIsNotNull() {
            addCriterion("FD_NEWS_BANNER is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerEqualTo(String value) {
            addCriterion("FD_NEWS_BANNER =", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerNotEqualTo(String value) {
            addCriterion("FD_NEWS_BANNER <>", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerGreaterThan(String value) {
            addCriterion("FD_NEWS_BANNER >", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerGreaterThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_BANNER >=", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerLessThan(String value) {
            addCriterion("FD_NEWS_BANNER <", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerLessThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_BANNER <=", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerLike(String value) {
            addCriterion("FD_NEWS_BANNER like", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerNotLike(String value) {
            addCriterion("FD_NEWS_BANNER not like", value, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerIn(List<String> values) {
            addCriterion("FD_NEWS_BANNER in", values, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerNotIn(List<String> values) {
            addCriterion("FD_NEWS_BANNER not in", values, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerBetween(String value1, String value2) {
            addCriterion("FD_NEWS_BANNER between", value1, value2, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsBannerNotBetween(String value1, String value2) {
            addCriterion("FD_NEWS_BANNER not between", value1, value2, "fdNewsBanner");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleIsNull() {
            addCriterion("FD_NEWS_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleIsNotNull() {
            addCriterion("FD_NEWS_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleEqualTo(String value) {
            addCriterion("FD_NEWS_TITLE =", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleNotEqualTo(String value) {
            addCriterion("FD_NEWS_TITLE <>", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleGreaterThan(String value) {
            addCriterion("FD_NEWS_TITLE >", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_TITLE >=", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleLessThan(String value) {
            addCriterion("FD_NEWS_TITLE <", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleLessThanOrEqualTo(String value) {
            addCriterion("FD_NEWS_TITLE <=", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleLike(String value) {
            addCriterion("FD_NEWS_TITLE like", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleNotLike(String value) {
            addCriterion("FD_NEWS_TITLE not like", value, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleIn(List<String> values) {
            addCriterion("FD_NEWS_TITLE in", values, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleNotIn(List<String> values) {
            addCriterion("FD_NEWS_TITLE not in", values, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleBetween(String value1, String value2) {
            addCriterion("FD_NEWS_TITLE between", value1, value2, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdNewsTitleNotBetween(String value1, String value2) {
            addCriterion("FD_NEWS_TITLE not between", value1, value2, "fdNewsTitle");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeIsNull() {
            addCriterion("FD_PUBLISH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeIsNotNull() {
            addCriterion("FD_PUBLISH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeEqualTo(String value) {
            addCriterion("FD_PUBLISH_TIME =", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeNotEqualTo(String value) {
            addCriterion("FD_PUBLISH_TIME <>", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeGreaterThan(String value) {
            addCriterion("FD_PUBLISH_TIME >", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISH_TIME >=", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeLessThan(String value) {
            addCriterion("FD_PUBLISH_TIME <", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeLessThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISH_TIME <=", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeLike(String value) {
            addCriterion("FD_PUBLISH_TIME like", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeNotLike(String value) {
            addCriterion("FD_PUBLISH_TIME not like", value, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeIn(List<String> values) {
            addCriterion("FD_PUBLISH_TIME in", values, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeNotIn(List<String> values) {
            addCriterion("FD_PUBLISH_TIME not in", values, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeBetween(String value1, String value2) {
            addCriterion("FD_PUBLISH_TIME between", value1, value2, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublishTimeNotBetween(String value1, String value2) {
            addCriterion("FD_PUBLISH_TIME not between", value1, value2, "fdPublishTime");
            return (Criteria) this;
        }

        public Criteria andFdPublisherIsNull() {
            addCriterion("FD_PUBLISHER is null");
            return (Criteria) this;
        }

        public Criteria andFdPublisherIsNotNull() {
            addCriterion("FD_PUBLISHER is not null");
            return (Criteria) this;
        }

        public Criteria andFdPublisherEqualTo(String value) {
            addCriterion("FD_PUBLISHER =", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherNotEqualTo(String value) {
            addCriterion("FD_PUBLISHER <>", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherGreaterThan(String value) {
            addCriterion("FD_PUBLISHER >", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISHER >=", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherLessThan(String value) {
            addCriterion("FD_PUBLISHER <", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherLessThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISHER <=", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherLike(String value) {
            addCriterion("FD_PUBLISHER like", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherNotLike(String value) {
            addCriterion("FD_PUBLISHER not like", value, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherIn(List<String> values) {
            addCriterion("FD_PUBLISHER in", values, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherNotIn(List<String> values) {
            addCriterion("FD_PUBLISHER not in", values, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherBetween(String value1, String value2) {
            addCriterion("FD_PUBLISHER between", value1, value2, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublisherNotBetween(String value1, String value2) {
            addCriterion("FD_PUBLISHER not between", value1, value2, "fdPublisher");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeIsNull() {
            addCriterion("FD_PUBLISH_NME is null");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeIsNotNull() {
            addCriterion("FD_PUBLISH_NME is not null");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeEqualTo(String value) {
            addCriterion("FD_PUBLISH_NME =", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeNotEqualTo(String value) {
            addCriterion("FD_PUBLISH_NME <>", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeGreaterThan(String value) {
            addCriterion("FD_PUBLISH_NME >", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISH_NME >=", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeLessThan(String value) {
            addCriterion("FD_PUBLISH_NME <", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeLessThanOrEqualTo(String value) {
            addCriterion("FD_PUBLISH_NME <=", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeLike(String value) {
            addCriterion("FD_PUBLISH_NME like", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeNotLike(String value) {
            addCriterion("FD_PUBLISH_NME not like", value, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeIn(List<String> values) {
            addCriterion("FD_PUBLISH_NME in", values, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeNotIn(List<String> values) {
            addCriterion("FD_PUBLISH_NME not in", values, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeBetween(String value1, String value2) {
            addCriterion("FD_PUBLISH_NME between", value1, value2, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdPublishNmeNotBetween(String value1, String value2) {
            addCriterion("FD_PUBLISH_NME not between", value1, value2, "fdPublishNme");
            return (Criteria) this;
        }

        public Criteria andFdValidflagIsNull() {
            addCriterion("FD_VALIDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andFdValidflagIsNotNull() {
            addCriterion("FD_VALIDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFdValidflagEqualTo(BigDecimal value) {
            addCriterion("FD_VALIDFLAG =", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagNotEqualTo(BigDecimal value) {
            addCriterion("FD_VALIDFLAG <>", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagGreaterThan(BigDecimal value) {
            addCriterion("FD_VALIDFLAG >", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_VALIDFLAG >=", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagLessThan(BigDecimal value) {
            addCriterion("FD_VALIDFLAG <", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_VALIDFLAG <=", value, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagIn(List<BigDecimal> values) {
            addCriterion("FD_VALIDFLAG in", values, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagNotIn(List<BigDecimal> values) {
            addCriterion("FD_VALIDFLAG not in", values, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_VALIDFLAG between", value1, value2, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdValidflagNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_VALIDFLAG not between", value1, value2, "fdValidflag");
            return (Criteria) this;
        }

        public Criteria andFdTopIsNull() {
            addCriterion("FD_TOP is null");
            return (Criteria) this;
        }

        public Criteria andFdTopIsNotNull() {
            addCriterion("FD_TOP is not null");
            return (Criteria) this;
        }

        public Criteria andFdTopEqualTo(BigDecimal value) {
            addCriterion("FD_TOP =", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopNotEqualTo(BigDecimal value) {
            addCriterion("FD_TOP <>", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopGreaterThan(BigDecimal value) {
            addCriterion("FD_TOP >", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_TOP >=", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopLessThan(BigDecimal value) {
            addCriterion("FD_TOP <", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_TOP <=", value, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopIn(List<BigDecimal> values) {
            addCriterion("FD_TOP in", values, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopNotIn(List<BigDecimal> values) {
            addCriterion("FD_TOP not in", values, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_TOP between", value1, value2, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdTopNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_TOP not between", value1, value2, "fdTop");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypIsNull() {
            addCriterion("FD_NEWS_SUB_TYP is null");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypIsNotNull() {
            addCriterion("FD_NEWS_SUB_TYP is not null");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypEqualTo(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP =", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypNotEqualTo(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP <>", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypGreaterThan(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP >", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP >=", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypLessThan(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP <", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_NEWS_SUB_TYP <=", value, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypIn(List<BigDecimal> values) {
            addCriterion("FD_NEWS_SUB_TYP in", values, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypNotIn(List<BigDecimal> values) {
            addCriterion("FD_NEWS_SUB_TYP not in", values, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_NEWS_SUB_TYP between", value1, value2, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdNewsSubTypNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_NEWS_SUB_TYP not between", value1, value2, "fdNewsSubTyp");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountIsNull() {
            addCriterion("FD_BROSWER_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountIsNotNull() {
            addCriterion("FD_BROSWER_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountEqualTo(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT =", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountNotEqualTo(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT <>", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountGreaterThan(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT >", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT >=", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountLessThan(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT <", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FD_BROSWER_COUNT <=", value, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountIn(List<BigDecimal> values) {
            addCriterion("FD_BROSWER_COUNT in", values, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountNotIn(List<BigDecimal> values) {
            addCriterion("FD_BROSWER_COUNT not in", values, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_BROSWER_COUNT between", value1, value2, "fdBroswerCount");
            return (Criteria) this;
        }

        public Criteria andFdBroswerCountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FD_BROSWER_COUNT not between", value1, value2, "fdBroswerCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 19 18:07:06 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_APP_DAILY_NEWS
     *
     * @mbggenerated Wed Apr 19 18:07:06 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}