package com.work.entity;

public class TbBlSupport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BL_SUPPORT.FD_SUPPORT_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    private String fdSupportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BL_SUPPORT.FD_REPLY_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    private String fdReplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BL_SUPPORT.FD_EMPID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    private String fdEmpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BL_SUPPORT.SUO_DATE
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    private String suoDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BL_SUPPORT.FD_SUPPORT_ID
     *
     * @return the value of TB_BL_SUPPORT.FD_SUPPORT_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public String getFdSupportId() {
        return fdSupportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BL_SUPPORT.FD_SUPPORT_ID
     *
     * @param fdSupportId the value for TB_BL_SUPPORT.FD_SUPPORT_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setFdSupportId(String fdSupportId) {
        this.fdSupportId = fdSupportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BL_SUPPORT.FD_REPLY_ID
     *
     * @return the value of TB_BL_SUPPORT.FD_REPLY_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public String getFdReplyId() {
        return fdReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BL_SUPPORT.FD_REPLY_ID
     *
     * @param fdReplyId the value for TB_BL_SUPPORT.FD_REPLY_ID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setFdReplyId(String fdReplyId) {
        this.fdReplyId = fdReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BL_SUPPORT.FD_EMPID
     *
     * @return the value of TB_BL_SUPPORT.FD_EMPID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public String getFdEmpid() {
        return fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BL_SUPPORT.FD_EMPID
     *
     * @param fdEmpid the value for TB_BL_SUPPORT.FD_EMPID
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setFdEmpid(String fdEmpid) {
        this.fdEmpid = fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BL_SUPPORT.SUO_DATE
     *
     * @return the value of TB_BL_SUPPORT.SUO_DATE
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public String getSuoDate() {
        return suoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BL_SUPPORT.SUO_DATE
     *
     * @param suoDate the value for TB_BL_SUPPORT.SUO_DATE
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setSuoDate(String suoDate) {
        this.suoDate = suoDate;
    }
}