package com.work.entity;

import java.util.ArrayList;
import java.util.List;

public class TbBlSupportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public TbBlSupportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFdSupportIdIsNull() {
            addCriterion("FD_SUPPORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdIsNotNull() {
            addCriterion("FD_SUPPORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdEqualTo(String value) {
            addCriterion("FD_SUPPORT_ID =", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdNotEqualTo(String value) {
            addCriterion("FD_SUPPORT_ID <>", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdGreaterThan(String value) {
            addCriterion("FD_SUPPORT_ID >", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdGreaterThanOrEqualTo(String value) {
            addCriterion("FD_SUPPORT_ID >=", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdLessThan(String value) {
            addCriterion("FD_SUPPORT_ID <", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdLessThanOrEqualTo(String value) {
            addCriterion("FD_SUPPORT_ID <=", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdLike(String value) {
            addCriterion("FD_SUPPORT_ID like", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdNotLike(String value) {
            addCriterion("FD_SUPPORT_ID not like", value, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdIn(List<String> values) {
            addCriterion("FD_SUPPORT_ID in", values, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdNotIn(List<String> values) {
            addCriterion("FD_SUPPORT_ID not in", values, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdBetween(String value1, String value2) {
            addCriterion("FD_SUPPORT_ID between", value1, value2, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdSupportIdNotBetween(String value1, String value2) {
            addCriterion("FD_SUPPORT_ID not between", value1, value2, "fdSupportId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdIsNull() {
            addCriterion("FD_REPLY_ID is null");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdIsNotNull() {
            addCriterion("FD_REPLY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdEqualTo(String value) {
            addCriterion("FD_REPLY_ID =", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdNotEqualTo(String value) {
            addCriterion("FD_REPLY_ID <>", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdGreaterThan(String value) {
            addCriterion("FD_REPLY_ID >", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("FD_REPLY_ID >=", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdLessThan(String value) {
            addCriterion("FD_REPLY_ID <", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdLessThanOrEqualTo(String value) {
            addCriterion("FD_REPLY_ID <=", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdLike(String value) {
            addCriterion("FD_REPLY_ID like", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdNotLike(String value) {
            addCriterion("FD_REPLY_ID not like", value, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdIn(List<String> values) {
            addCriterion("FD_REPLY_ID in", values, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdNotIn(List<String> values) {
            addCriterion("FD_REPLY_ID not in", values, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdBetween(String value1, String value2) {
            addCriterion("FD_REPLY_ID between", value1, value2, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdReplyIdNotBetween(String value1, String value2) {
            addCriterion("FD_REPLY_ID not between", value1, value2, "fdReplyId");
            return (Criteria) this;
        }

        public Criteria andFdEmpidIsNull() {
            addCriterion("FD_EMPID is null");
            return (Criteria) this;
        }

        public Criteria andFdEmpidIsNotNull() {
            addCriterion("FD_EMPID is not null");
            return (Criteria) this;
        }

        public Criteria andFdEmpidEqualTo(String value) {
            addCriterion("FD_EMPID =", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidNotEqualTo(String value) {
            addCriterion("FD_EMPID <>", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidGreaterThan(String value) {
            addCriterion("FD_EMPID >", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidGreaterThanOrEqualTo(String value) {
            addCriterion("FD_EMPID >=", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidLessThan(String value) {
            addCriterion("FD_EMPID <", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidLessThanOrEqualTo(String value) {
            addCriterion("FD_EMPID <=", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidLike(String value) {
            addCriterion("FD_EMPID like", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidNotLike(String value) {
            addCriterion("FD_EMPID not like", value, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidIn(List<String> values) {
            addCriterion("FD_EMPID in", values, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidNotIn(List<String> values) {
            addCriterion("FD_EMPID not in", values, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidBetween(String value1, String value2) {
            addCriterion("FD_EMPID between", value1, value2, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andFdEmpidNotBetween(String value1, String value2) {
            addCriterion("FD_EMPID not between", value1, value2, "fdEmpid");
            return (Criteria) this;
        }

        public Criteria andSuoDateIsNull() {
            addCriterion("SUO_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSuoDateIsNotNull() {
            addCriterion("SUO_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSuoDateEqualTo(String value) {
            addCriterion("SUO_DATE =", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateNotEqualTo(String value) {
            addCriterion("SUO_DATE <>", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateGreaterThan(String value) {
            addCriterion("SUO_DATE >", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateGreaterThanOrEqualTo(String value) {
            addCriterion("SUO_DATE >=", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateLessThan(String value) {
            addCriterion("SUO_DATE <", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateLessThanOrEqualTo(String value) {
            addCriterion("SUO_DATE <=", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateLike(String value) {
            addCriterion("SUO_DATE like", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateNotLike(String value) {
            addCriterion("SUO_DATE not like", value, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateIn(List<String> values) {
            addCriterion("SUO_DATE in", values, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateNotIn(List<String> values) {
            addCriterion("SUO_DATE not in", values, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateBetween(String value1, String value2) {
            addCriterion("SUO_DATE between", value1, value2, "suoDate");
            return (Criteria) this;
        }

        public Criteria andSuoDateNotBetween(String value1, String value2) {
            addCriterion("SUO_DATE not between", value1, value2, "suoDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 19 09:34:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_SUPPORT
     *
     * @mbggenerated Wed Apr 19 09:34:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}