package com.work.entity;

import java.util.ArrayList;
import java.util.List;

public class TbBlBlogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public TbBlBlogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFdBlIdIsNull() {
            addCriterion("FD_BL_ID is null");
            return (Criteria) this;
        }

        public Criteria andFdBlIdIsNotNull() {
            addCriterion("FD_BL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFdBlIdEqualTo(String value) {
            addCriterion("FD_BL_ID =", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdNotEqualTo(String value) {
            addCriterion("FD_BL_ID <>", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdGreaterThan(String value) {
            addCriterion("FD_BL_ID >", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdGreaterThanOrEqualTo(String value) {
            addCriterion("FD_BL_ID >=", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdLessThan(String value) {
            addCriterion("FD_BL_ID <", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdLessThanOrEqualTo(String value) {
            addCriterion("FD_BL_ID <=", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdLike(String value) {
            addCriterion("FD_BL_ID like", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdNotLike(String value) {
            addCriterion("FD_BL_ID not like", value, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdIn(List<String> values) {
            addCriterion("FD_BL_ID in", values, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdNotIn(List<String> values) {
            addCriterion("FD_BL_ID not in", values, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdBetween(String value1, String value2) {
            addCriterion("FD_BL_ID between", value1, value2, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlIdNotBetween(String value1, String value2) {
            addCriterion("FD_BL_ID not between", value1, value2, "fdBlId");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleIsNull() {
            addCriterion("FD_BL_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleIsNotNull() {
            addCriterion("FD_BL_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleEqualTo(String value) {
            addCriterion("FD_BL_TITLE =", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleNotEqualTo(String value) {
            addCriterion("FD_BL_TITLE <>", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleGreaterThan(String value) {
            addCriterion("FD_BL_TITLE >", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleGreaterThanOrEqualTo(String value) {
            addCriterion("FD_BL_TITLE >=", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleLessThan(String value) {
            addCriterion("FD_BL_TITLE <", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleLessThanOrEqualTo(String value) {
            addCriterion("FD_BL_TITLE <=", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleLike(String value) {
            addCriterion("FD_BL_TITLE like", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleNotLike(String value) {
            addCriterion("FD_BL_TITLE not like", value, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleIn(List<String> values) {
            addCriterion("FD_BL_TITLE in", values, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleNotIn(List<String> values) {
            addCriterion("FD_BL_TITLE not in", values, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleBetween(String value1, String value2) {
            addCriterion("FD_BL_TITLE between", value1, value2, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlTitleNotBetween(String value1, String value2) {
            addCriterion("FD_BL_TITLE not between", value1, value2, "fdBlTitle");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidIsNull() {
            addCriterion("FD_BL_CREATEID is null");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidIsNotNull() {
            addCriterion("FD_BL_CREATEID is not null");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidEqualTo(String value) {
            addCriterion("FD_BL_CREATEID =", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidNotEqualTo(String value) {
            addCriterion("FD_BL_CREATEID <>", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidGreaterThan(String value) {
            addCriterion("FD_BL_CREATEID >", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidGreaterThanOrEqualTo(String value) {
            addCriterion("FD_BL_CREATEID >=", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidLessThan(String value) {
            addCriterion("FD_BL_CREATEID <", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidLessThanOrEqualTo(String value) {
            addCriterion("FD_BL_CREATEID <=", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidLike(String value) {
            addCriterion("FD_BL_CREATEID like", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidNotLike(String value) {
            addCriterion("FD_BL_CREATEID not like", value, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidIn(List<String> values) {
            addCriterion("FD_BL_CREATEID in", values, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidNotIn(List<String> values) {
            addCriterion("FD_BL_CREATEID not in", values, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidBetween(String value1, String value2) {
            addCriterion("FD_BL_CREATEID between", value1, value2, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdBlCreateidNotBetween(String value1, String value2) {
            addCriterion("FD_BL_CREATEID not between", value1, value2, "fdBlCreateid");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIsNull() {
            addCriterion("FD_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIsNotNull() {
            addCriterion("FD_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeEqualTo(String value) {
            addCriterion("FD_CREATE_TIME =", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotEqualTo(String value) {
            addCriterion("FD_CREATE_TIME <>", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeGreaterThan(String value) {
            addCriterion("FD_CREATE_TIME >", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_CREATE_TIME >=", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeLessThan(String value) {
            addCriterion("FD_CREATE_TIME <", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("FD_CREATE_TIME <=", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeLike(String value) {
            addCriterion("FD_CREATE_TIME like", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotLike(String value) {
            addCriterion("FD_CREATE_TIME not like", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIn(List<String> values) {
            addCriterion("FD_CREATE_TIME in", values, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotIn(List<String> values) {
            addCriterion("FD_CREATE_TIME not in", values, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeBetween(String value1, String value2) {
            addCriterion("FD_CREATE_TIME between", value1, value2, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotBetween(String value1, String value2) {
            addCriterion("FD_CREATE_TIME not between", value1, value2, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeIsNull() {
            addCriterion("FD_CREATE_DEPNME is null");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeIsNotNull() {
            addCriterion("FD_CREATE_DEPNME is not null");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeEqualTo(String value) {
            addCriterion("FD_CREATE_DEPNME =", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeNotEqualTo(String value) {
            addCriterion("FD_CREATE_DEPNME <>", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeGreaterThan(String value) {
            addCriterion("FD_CREATE_DEPNME >", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_CREATE_DEPNME >=", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeLessThan(String value) {
            addCriterion("FD_CREATE_DEPNME <", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeLessThanOrEqualTo(String value) {
            addCriterion("FD_CREATE_DEPNME <=", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeLike(String value) {
            addCriterion("FD_CREATE_DEPNME like", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeNotLike(String value) {
            addCriterion("FD_CREATE_DEPNME not like", value, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeIn(List<String> values) {
            addCriterion("FD_CREATE_DEPNME in", values, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeNotIn(List<String> values) {
            addCriterion("FD_CREATE_DEPNME not in", values, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeBetween(String value1, String value2) {
            addCriterion("FD_CREATE_DEPNME between", value1, value2, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdCreateDepnmeNotBetween(String value1, String value2) {
            addCriterion("FD_CREATE_DEPNME not between", value1, value2, "fdCreateDepnme");
            return (Criteria) this;
        }

        public Criteria andFdReadCountIsNull() {
            addCriterion("FD_READ_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andFdReadCountIsNotNull() {
            addCriterion("FD_READ_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFdReadCountEqualTo(String value) {
            addCriterion("FD_READ_COUNT =", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountNotEqualTo(String value) {
            addCriterion("FD_READ_COUNT <>", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountGreaterThan(String value) {
            addCriterion("FD_READ_COUNT >", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountGreaterThanOrEqualTo(String value) {
            addCriterion("FD_READ_COUNT >=", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountLessThan(String value) {
            addCriterion("FD_READ_COUNT <", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountLessThanOrEqualTo(String value) {
            addCriterion("FD_READ_COUNT <=", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountLike(String value) {
            addCriterion("FD_READ_COUNT like", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountNotLike(String value) {
            addCriterion("FD_READ_COUNT not like", value, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountIn(List<String> values) {
            addCriterion("FD_READ_COUNT in", values, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountNotIn(List<String> values) {
            addCriterion("FD_READ_COUNT not in", values, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountBetween(String value1, String value2) {
            addCriterion("FD_READ_COUNT between", value1, value2, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdReadCountNotBetween(String value1, String value2) {
            addCriterion("FD_READ_COUNT not between", value1, value2, "fdReadCount");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdIsNull() {
            addCriterion("FD_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdIsNotNull() {
            addCriterion("FD_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdEqualTo(String value) {
            addCriterion("FD_TYPE_ID =", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdNotEqualTo(String value) {
            addCriterion("FD_TYPE_ID <>", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdGreaterThan(String value) {
            addCriterion("FD_TYPE_ID >", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("FD_TYPE_ID >=", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdLessThan(String value) {
            addCriterion("FD_TYPE_ID <", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdLessThanOrEqualTo(String value) {
            addCriterion("FD_TYPE_ID <=", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdLike(String value) {
            addCriterion("FD_TYPE_ID like", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdNotLike(String value) {
            addCriterion("FD_TYPE_ID not like", value, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdIn(List<String> values) {
            addCriterion("FD_TYPE_ID in", values, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdNotIn(List<String> values) {
            addCriterion("FD_TYPE_ID not in", values, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdBetween(String value1, String value2) {
            addCriterion("FD_TYPE_ID between", value1, value2, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeIdNotBetween(String value1, String value2) {
            addCriterion("FD_TYPE_ID not between", value1, value2, "fdTypeId");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeIsNull() {
            addCriterion("FD_TYPE_NME is null");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeIsNotNull() {
            addCriterion("FD_TYPE_NME is not null");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeEqualTo(String value) {
            addCriterion("FD_TYPE_NME =", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeNotEqualTo(String value) {
            addCriterion("FD_TYPE_NME <>", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeGreaterThan(String value) {
            addCriterion("FD_TYPE_NME >", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_TYPE_NME >=", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeLessThan(String value) {
            addCriterion("FD_TYPE_NME <", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeLessThanOrEqualTo(String value) {
            addCriterion("FD_TYPE_NME <=", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeLike(String value) {
            addCriterion("FD_TYPE_NME like", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeNotLike(String value) {
            addCriterion("FD_TYPE_NME not like", value, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeIn(List<String> values) {
            addCriterion("FD_TYPE_NME in", values, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeNotIn(List<String> values) {
            addCriterion("FD_TYPE_NME not in", values, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeBetween(String value1, String value2) {
            addCriterion("FD_TYPE_NME between", value1, value2, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdTypeNmeNotBetween(String value1, String value2) {
            addCriterion("FD_TYPE_NME not between", value1, value2, "fdTypeNme");
            return (Criteria) this;
        }

        public Criteria andFdShowIsNull() {
            addCriterion("FD_SHOW is null");
            return (Criteria) this;
        }

        public Criteria andFdShowIsNotNull() {
            addCriterion("FD_SHOW is not null");
            return (Criteria) this;
        }

        public Criteria andFdShowEqualTo(String value) {
            addCriterion("FD_SHOW =", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowNotEqualTo(String value) {
            addCriterion("FD_SHOW <>", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowGreaterThan(String value) {
            addCriterion("FD_SHOW >", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowGreaterThanOrEqualTo(String value) {
            addCriterion("FD_SHOW >=", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowLessThan(String value) {
            addCriterion("FD_SHOW <", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowLessThanOrEqualTo(String value) {
            addCriterion("FD_SHOW <=", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowLike(String value) {
            addCriterion("FD_SHOW like", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowNotLike(String value) {
            addCriterion("FD_SHOW not like", value, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowIn(List<String> values) {
            addCriterion("FD_SHOW in", values, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowNotIn(List<String> values) {
            addCriterion("FD_SHOW not in", values, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowBetween(String value1, String value2) {
            addCriterion("FD_SHOW between", value1, value2, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdShowNotBetween(String value1, String value2) {
            addCriterion("FD_SHOW not between", value1, value2, "fdShow");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeIsNull() {
            addCriterion("FD_EMP_NME is null");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeIsNotNull() {
            addCriterion("FD_EMP_NME is not null");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeEqualTo(String value) {
            addCriterion("FD_EMP_NME =", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeNotEqualTo(String value) {
            addCriterion("FD_EMP_NME <>", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeGreaterThan(String value) {
            addCriterion("FD_EMP_NME >", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_EMP_NME >=", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeLessThan(String value) {
            addCriterion("FD_EMP_NME <", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeLessThanOrEqualTo(String value) {
            addCriterion("FD_EMP_NME <=", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeLike(String value) {
            addCriterion("FD_EMP_NME like", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeNotLike(String value) {
            addCriterion("FD_EMP_NME not like", value, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeIn(List<String> values) {
            addCriterion("FD_EMP_NME in", values, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeNotIn(List<String> values) {
            addCriterion("FD_EMP_NME not in", values, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeBetween(String value1, String value2) {
            addCriterion("FD_EMP_NME between", value1, value2, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdEmpNmeNotBetween(String value1, String value2) {
            addCriterion("FD_EMP_NME not between", value1, value2, "fdEmpNme");
            return (Criteria) this;
        }

        public Criteria andFdBlSupIsNull() {
            addCriterion("FD_BL_SUP is null");
            return (Criteria) this;
        }

        public Criteria andFdBlSupIsNotNull() {
            addCriterion("FD_BL_SUP is not null");
            return (Criteria) this;
        }

        public Criteria andFdBlSupEqualTo(String value) {
            addCriterion("FD_BL_SUP =", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupNotEqualTo(String value) {
            addCriterion("FD_BL_SUP <>", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupGreaterThan(String value) {
            addCriterion("FD_BL_SUP >", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupGreaterThanOrEqualTo(String value) {
            addCriterion("FD_BL_SUP >=", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupLessThan(String value) {
            addCriterion("FD_BL_SUP <", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupLessThanOrEqualTo(String value) {
            addCriterion("FD_BL_SUP <=", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupLike(String value) {
            addCriterion("FD_BL_SUP like", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupNotLike(String value) {
            addCriterion("FD_BL_SUP not like", value, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupIn(List<String> values) {
            addCriterion("FD_BL_SUP in", values, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupNotIn(List<String> values) {
            addCriterion("FD_BL_SUP not in", values, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupBetween(String value1, String value2) {
            addCriterion("FD_BL_SUP between", value1, value2, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlSupNotBetween(String value1, String value2) {
            addCriterion("FD_BL_SUP not between", value1, value2, "fdBlSup");
            return (Criteria) this;
        }

        public Criteria andFdBlDissIsNull() {
            addCriterion("FD_BL_DISS is null");
            return (Criteria) this;
        }

        public Criteria andFdBlDissIsNotNull() {
            addCriterion("FD_BL_DISS is not null");
            return (Criteria) this;
        }

        public Criteria andFdBlDissEqualTo(String value) {
            addCriterion("FD_BL_DISS =", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissNotEqualTo(String value) {
            addCriterion("FD_BL_DISS <>", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissGreaterThan(String value) {
            addCriterion("FD_BL_DISS >", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissGreaterThanOrEqualTo(String value) {
            addCriterion("FD_BL_DISS >=", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissLessThan(String value) {
            addCriterion("FD_BL_DISS <", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissLessThanOrEqualTo(String value) {
            addCriterion("FD_BL_DISS <=", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissLike(String value) {
            addCriterion("FD_BL_DISS like", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissNotLike(String value) {
            addCriterion("FD_BL_DISS not like", value, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissIn(List<String> values) {
            addCriterion("FD_BL_DISS in", values, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissNotIn(List<String> values) {
            addCriterion("FD_BL_DISS not in", values, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissBetween(String value1, String value2) {
            addCriterion("FD_BL_DISS between", value1, value2, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdBlDissNotBetween(String value1, String value2) {
            addCriterion("FD_BL_DISS not between", value1, value2, "fdBlDiss");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeIsNull() {
            addCriterion("FD_ORGCDE is null");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeIsNotNull() {
            addCriterion("FD_ORGCDE is not null");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeEqualTo(String value) {
            addCriterion("FD_ORGCDE =", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeNotEqualTo(String value) {
            addCriterion("FD_ORGCDE <>", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeGreaterThan(String value) {
            addCriterion("FD_ORGCDE >", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeGreaterThanOrEqualTo(String value) {
            addCriterion("FD_ORGCDE >=", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeLessThan(String value) {
            addCriterion("FD_ORGCDE <", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeLessThanOrEqualTo(String value) {
            addCriterion("FD_ORGCDE <=", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeLike(String value) {
            addCriterion("FD_ORGCDE like", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeNotLike(String value) {
            addCriterion("FD_ORGCDE not like", value, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeIn(List<String> values) {
            addCriterion("FD_ORGCDE in", values, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeNotIn(List<String> values) {
            addCriterion("FD_ORGCDE not in", values, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeBetween(String value1, String value2) {
            addCriterion("FD_ORGCDE between", value1, value2, "fdOrgcde");
            return (Criteria) this;
        }

        public Criteria andFdOrgcdeNotBetween(String value1, String value2) {
            addCriterion("FD_ORGCDE not between", value1, value2, "fdOrgcde");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 07 15:52:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BL_BLOG
     *
     * @mbggenerated Fri Apr 07 15:52:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}