package com.work.entity;

import java.math.BigDecimal;

public class TbPepmgmLeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PEPMGM_LEADER.FD_EMPID
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    private String fdEmpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PEPMGM_LEADER.FD_LEVEL
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    private BigDecimal fdLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PEPMGM_LEADER.FD_PARENT_EMP
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    private String fdParentEmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PEPMGM_LEADER.FD_EMPID
     *
     * @return the value of TB_PEPMGM_LEADER.FD_EMPID
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public String getFdEmpid() {
        return fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PEPMGM_LEADER.FD_EMPID
     *
     * @param fdEmpid the value for TB_PEPMGM_LEADER.FD_EMPID
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public void setFdEmpid(String fdEmpid) {
        this.fdEmpid = fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PEPMGM_LEADER.FD_LEVEL
     *
     * @return the value of TB_PEPMGM_LEADER.FD_LEVEL
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public BigDecimal getFdLevel() {
        return fdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PEPMGM_LEADER.FD_LEVEL
     *
     * @param fdLevel the value for TB_PEPMGM_LEADER.FD_LEVEL
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public void setFdLevel(BigDecimal fdLevel) {
        this.fdLevel = fdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PEPMGM_LEADER.FD_PARENT_EMP
     *
     * @return the value of TB_PEPMGM_LEADER.FD_PARENT_EMP
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public String getFdParentEmp() {
        return fdParentEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PEPMGM_LEADER.FD_PARENT_EMP
     *
     * @param fdParentEmp the value for TB_PEPMGM_LEADER.FD_PARENT_EMP
     *
     * @mbggenerated Mon Jan 08 14:53:53 CST 2018
     */
    public void setFdParentEmp(String fdParentEmp) {
        this.fdParentEmp = fdParentEmp;
    }
}