package com.work.entity;

import java.math.BigDecimal;

public class TbSysOrginfoEhr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_SYSTEMNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgSystemno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdParentOrgcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgnme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ENGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdEngnme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGALIAS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgalias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrglevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_COUNTRY
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_DIVISION
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdDivision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_LEGALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdLegaladdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ACTUALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdActualaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_HEAD
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_RENT_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private BigDecimal fdRentArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_OWNED_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private BigDecimal fdOwnedArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_BASE_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdBaseOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_STR_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdStrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_FAX
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_POSTCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdPostcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_VALIDFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdValidflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_OPERATINGSTATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOperatingstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ACCORDINGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdAccordinglevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_LEGALHEAD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgLegalheadTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_SWIFT_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdSwiftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_TELEXNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgTelexno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_REPORTORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdReportorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdParentOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGDIFPROV_PREFIXNUM
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgdifprovPrefixnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ENTER_SYSTEMTYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdEnterSystemtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_SETUPBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdSetupbasisRefereno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_OPENTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdAccountingOpentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_CANCELBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdCancelbasisRefereno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_CANCELTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdAccountingCanceltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_DATATYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdDatatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_LOGITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgLogitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_LATITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORG_ADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_LEGALPERSON_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdLegalpersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_GLOBAL_DISPLAYORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdGlobalDisplayorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_PARENTID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private BigDecimal fdOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_NODEID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdNodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGSHORT
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgshort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_ORGTYP
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdOrgtyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SYS_ORGINFO_EHR.FD_END_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    private String fdEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_SYSTEMNO
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_SYSTEMNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgSystemno() {
        return fdOrgSystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_SYSTEMNO
     *
     * @param fdOrgSystemno the value for TB_SYS_ORGINFO_EHR.FD_ORG_SYSTEMNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgSystemno(String fdOrgSystemno) {
        this.fdOrgSystemno = fdOrgSystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORGCDE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_PARENT_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdParentOrgcde() {
        return fdParentOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORGCDE
     *
     * @param fdParentOrgcde the value for TB_SYS_ORGINFO_EHR.FD_PARENT_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdParentOrgcde(String fdParentOrgcde) {
        this.fdParentOrgcde = fdParentOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGCDE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgcde() {
        return fdOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGCDE
     *
     * @param fdOrgcde the value for TB_SYS_ORGINFO_EHR.FD_ORGCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgcde(String fdOrgcde) {
        this.fdOrgcde = fdOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGNME
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgnme() {
        return fdOrgnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGNME
     *
     * @param fdOrgnme the value for TB_SYS_ORGINFO_EHR.FD_ORGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgnme(String fdOrgnme) {
        this.fdOrgnme = fdOrgnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ENGNME
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ENGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdEngnme() {
        return fdEngnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ENGNME
     *
     * @param fdEngnme the value for TB_SYS_ORGINFO_EHR.FD_ENGNME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdEngnme(String fdEngnme) {
        this.fdEngnme = fdEngnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGALIAS
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGALIAS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgalias() {
        return fdOrgalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGALIAS
     *
     * @param fdOrgalias the value for TB_SYS_ORGINFO_EHR.FD_ORGALIAS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgalias(String fdOrgalias) {
        this.fdOrgalias = fdOrgalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGFLAG
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgflag() {
        return fdOrgflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGFLAG
     *
     * @param fdOrgflag the value for TB_SYS_ORGINFO_EHR.FD_ORGFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgflag(String fdOrgflag) {
        this.fdOrgflag = fdOrgflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGLEVEL
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrglevel() {
        return fdOrglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGLEVEL
     *
     * @param fdOrglevel the value for TB_SYS_ORGINFO_EHR.FD_ORGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrglevel(String fdOrglevel) {
        this.fdOrglevel = fdOrglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_COUNTRY
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_COUNTRY
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdCountry() {
        return fdCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_COUNTRY
     *
     * @param fdCountry the value for TB_SYS_ORGINFO_EHR.FD_COUNTRY
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdCountry(String fdCountry) {
        this.fdCountry = fdCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_AREA
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdArea() {
        return fdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_AREA
     *
     * @param fdArea the value for TB_SYS_ORGINFO_EHR.FD_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdArea(String fdArea) {
        this.fdArea = fdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_DIVISION
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_DIVISION
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdDivision() {
        return fdDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_DIVISION
     *
     * @param fdDivision the value for TB_SYS_ORGINFO_EHR.FD_DIVISION
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdDivision(String fdDivision) {
        this.fdDivision = fdDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_LEGALADDRESS
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_LEGALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdLegaladdress() {
        return fdLegaladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_LEGALADDRESS
     *
     * @param fdLegaladdress the value for TB_SYS_ORGINFO_EHR.FD_LEGALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdLegaladdress(String fdLegaladdress) {
        this.fdLegaladdress = fdLegaladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ACTUALADDRESS
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ACTUALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdActualaddress() {
        return fdActualaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ACTUALADDRESS
     *
     * @param fdActualaddress the value for TB_SYS_ORGINFO_EHR.FD_ACTUALADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdActualaddress(String fdActualaddress) {
        this.fdActualaddress = fdActualaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_HEAD
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_HEAD
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdHead() {
        return fdHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_HEAD
     *
     * @param fdHead the value for TB_SYS_ORGINFO_EHR.FD_HEAD
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdHead(String fdHead) {
        this.fdHead = fdHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_RENT_AREA
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_RENT_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public BigDecimal getFdRentArea() {
        return fdRentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_RENT_AREA
     *
     * @param fdRentArea the value for TB_SYS_ORGINFO_EHR.FD_RENT_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdRentArea(BigDecimal fdRentArea) {
        this.fdRentArea = fdRentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_OWNED_AREA
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_OWNED_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public BigDecimal getFdOwnedArea() {
        return fdOwnedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_OWNED_AREA
     *
     * @param fdOwnedArea the value for TB_SYS_ORGINFO_EHR.FD_OWNED_AREA
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOwnedArea(BigDecimal fdOwnedArea) {
        this.fdOwnedArea = fdOwnedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_TEL
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdTel() {
        return fdTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_TEL
     *
     * @param fdTel the value for TB_SYS_ORGINFO_EHR.FD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdTel(String fdTel) {
        this.fdTel = fdTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_BASE_ORG
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_BASE_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdBaseOrg() {
        return fdBaseOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_BASE_ORG
     *
     * @param fdBaseOrg the value for TB_SYS_ORGINFO_EHR.FD_BASE_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdBaseOrg(String fdBaseOrg) {
        this.fdBaseOrg = fdBaseOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_STR_DATE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_STR_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdStrDate() {
        return fdStrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_STR_DATE
     *
     * @param fdStrDate the value for TB_SYS_ORGINFO_EHR.FD_STR_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdStrDate(String fdStrDate) {
        this.fdStrDate = fdStrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_FAX
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_FAX
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdFax() {
        return fdFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_FAX
     *
     * @param fdFax the value for TB_SYS_ORGINFO_EHR.FD_FAX
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdFax(String fdFax) {
        this.fdFax = fdFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_POSTCDE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_POSTCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdPostcde() {
        return fdPostcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_POSTCDE
     *
     * @param fdPostcde the value for TB_SYS_ORGINFO_EHR.FD_POSTCDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdPostcde(String fdPostcde) {
        this.fdPostcde = fdPostcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_VALIDFLAG
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_VALIDFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdValidflag() {
        return fdValidflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_VALIDFLAG
     *
     * @param fdValidflag the value for TB_SYS_ORGINFO_EHR.FD_VALIDFLAG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdValidflag(String fdValidflag) {
        this.fdValidflag = fdValidflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_OPERATINGSTATE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_OPERATINGSTATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOperatingstate() {
        return fdOperatingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_OPERATINGSTATE
     *
     * @param fdOperatingstate the value for TB_SYS_ORGINFO_EHR.FD_OPERATINGSTATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOperatingstate(String fdOperatingstate) {
        this.fdOperatingstate = fdOperatingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCORDINGLEVEL
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ACCORDINGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdAccordinglevel() {
        return fdAccordinglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCORDINGLEVEL
     *
     * @param fdAccordinglevel the value for TB_SYS_ORGINFO_EHR.FD_ACCORDINGLEVEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdAccordinglevel(String fdAccordinglevel) {
        this.fdAccordinglevel = fdAccordinglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LEGALHEAD_TEL
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_LEGALHEAD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgLegalheadTel() {
        return fdOrgLegalheadTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LEGALHEAD_TEL
     *
     * @param fdOrgLegalheadTel the value for TB_SYS_ORGINFO_EHR.FD_ORG_LEGALHEAD_TEL
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgLegalheadTel(String fdOrgLegalheadTel) {
        this.fdOrgLegalheadTel = fdOrgLegalheadTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_SWIFT_ID
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_SWIFT_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdSwiftId() {
        return fdSwiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_SWIFT_ID
     *
     * @param fdSwiftId the value for TB_SYS_ORGINFO_EHR.FD_SWIFT_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdSwiftId(String fdSwiftId) {
        this.fdSwiftId = fdSwiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_TELEXNO
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_TELEXNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgTelexno() {
        return fdOrgTelexno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_TELEXNO
     *
     * @param fdOrgTelexno the value for TB_SYS_ORGINFO_EHR.FD_ORG_TELEXNO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgTelexno(String fdOrgTelexno) {
        this.fdOrgTelexno = fdOrgTelexno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_REPORTORG
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_REPORTORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdReportorg() {
        return fdReportorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_REPORTORG
     *
     * @param fdReportorg the value for TB_SYS_ORGINFO_EHR.FD_REPORTORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdReportorg(String fdReportorg) {
        this.fdReportorg = fdReportorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORG
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_PARENT_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdParentOrg() {
        return fdParentOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENT_ORG
     *
     * @param fdParentOrg the value for TB_SYS_ORGINFO_EHR.FD_PARENT_ORG
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdParentOrg(String fdParentOrg) {
        this.fdParentOrg = fdParentOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGDIFPROV_PREFIXNUM
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGDIFPROV_PREFIXNUM
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgdifprovPrefixnum() {
        return fdOrgdifprovPrefixnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGDIFPROV_PREFIXNUM
     *
     * @param fdOrgdifprovPrefixnum the value for TB_SYS_ORGINFO_EHR.FD_ORGDIFPROV_PREFIXNUM
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgdifprovPrefixnum(String fdOrgdifprovPrefixnum) {
        this.fdOrgdifprovPrefixnum = fdOrgdifprovPrefixnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ENTER_SYSTEMTYPE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ENTER_SYSTEMTYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdEnterSystemtype() {
        return fdEnterSystemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ENTER_SYSTEMTYPE
     *
     * @param fdEnterSystemtype the value for TB_SYS_ORGINFO_EHR.FD_ENTER_SYSTEMTYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdEnterSystemtype(String fdEnterSystemtype) {
        this.fdEnterSystemtype = fdEnterSystemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_SETUPBASIS_REFERENO
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_SETUPBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdSetupbasisRefereno() {
        return fdSetupbasisRefereno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_SETUPBASIS_REFERENO
     *
     * @param fdSetupbasisRefereno the value for TB_SYS_ORGINFO_EHR.FD_SETUPBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdSetupbasisRefereno(String fdSetupbasisRefereno) {
        this.fdSetupbasisRefereno = fdSetupbasisRefereno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_OPENTIME
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_OPENTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdAccountingOpentime() {
        return fdAccountingOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_OPENTIME
     *
     * @param fdAccountingOpentime the value for TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_OPENTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdAccountingOpentime(String fdAccountingOpentime) {
        this.fdAccountingOpentime = fdAccountingOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_CANCELBASIS_REFERENO
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_CANCELBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdCancelbasisRefereno() {
        return fdCancelbasisRefereno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_CANCELBASIS_REFERENO
     *
     * @param fdCancelbasisRefereno the value for TB_SYS_ORGINFO_EHR.FD_CANCELBASIS_REFERENO
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdCancelbasisRefereno(String fdCancelbasisRefereno) {
        this.fdCancelbasisRefereno = fdCancelbasisRefereno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_CANCELTIME
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_CANCELTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdAccountingCanceltime() {
        return fdAccountingCanceltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_CANCELTIME
     *
     * @param fdAccountingCanceltime the value for TB_SYS_ORGINFO_EHR.FD_ACCOUNTING_CANCELTIME
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdAccountingCanceltime(String fdAccountingCanceltime) {
        this.fdAccountingCanceltime = fdAccountingCanceltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_DATATYPE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_DATATYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdDatatype() {
        return fdDatatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_DATATYPE
     *
     * @param fdDatatype the value for TB_SYS_ORGINFO_EHR.FD_DATATYPE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdDatatype(String fdDatatype) {
        this.fdDatatype = fdDatatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LOGITUDE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_LOGITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgLogitude() {
        return fdOrgLogitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LOGITUDE
     *
     * @param fdOrgLogitude the value for TB_SYS_ORGINFO_EHR.FD_ORG_LOGITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgLogitude(String fdOrgLogitude) {
        this.fdOrgLogitude = fdOrgLogitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LATITUDE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_LATITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgLatitude() {
        return fdOrgLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_LATITUDE
     *
     * @param fdOrgLatitude the value for TB_SYS_ORGINFO_EHR.FD_ORG_LATITUDE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgLatitude(String fdOrgLatitude) {
        this.fdOrgLatitude = fdOrgLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_ADDRESS
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORG_ADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgAddress() {
        return fdOrgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORG_ADDRESS
     *
     * @param fdOrgAddress the value for TB_SYS_ORGINFO_EHR.FD_ORG_ADDRESS
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgAddress(String fdOrgAddress) {
        this.fdOrgAddress = fdOrgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_LEGALPERSON_ID
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_LEGALPERSON_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdLegalpersonId() {
        return fdLegalpersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_LEGALPERSON_ID
     *
     * @param fdLegalpersonId the value for TB_SYS_ORGINFO_EHR.FD_LEGALPERSON_ID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdLegalpersonId(String fdLegalpersonId) {
        this.fdLegalpersonId = fdLegalpersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_GLOBAL_DISPLAYORDER
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_GLOBAL_DISPLAYORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdGlobalDisplayorder() {
        return fdGlobalDisplayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_GLOBAL_DISPLAYORDER
     *
     * @param fdGlobalDisplayorder the value for TB_SYS_ORGINFO_EHR.FD_GLOBAL_DISPLAYORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdGlobalDisplayorder(String fdGlobalDisplayorder) {
        this.fdGlobalDisplayorder = fdGlobalDisplayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENTID
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_PARENTID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdParentid() {
        return fdParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_PARENTID
     *
     * @param fdParentid the value for TB_SYS_ORGINFO_EHR.FD_PARENTID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdParentid(String fdParentid) {
        this.fdParentid = fdParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORDER
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public BigDecimal getFdOrder() {
        return fdOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORDER
     *
     * @param fdOrder the value for TB_SYS_ORGINFO_EHR.FD_ORDER
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrder(BigDecimal fdOrder) {
        this.fdOrder = fdOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_NODEID
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_NODEID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdNodeid() {
        return fdNodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_NODEID
     *
     * @param fdNodeid the value for TB_SYS_ORGINFO_EHR.FD_NODEID
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdNodeid(String fdNodeid) {
        this.fdNodeid = fdNodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGSHORT
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGSHORT
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgshort() {
        return fdOrgshort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGSHORT
     *
     * @param fdOrgshort the value for TB_SYS_ORGINFO_EHR.FD_ORGSHORT
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgshort(String fdOrgshort) {
        this.fdOrgshort = fdOrgshort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGTYP
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_ORGTYP
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdOrgtyp() {
        return fdOrgtyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_ORGTYP
     *
     * @param fdOrgtyp the value for TB_SYS_ORGINFO_EHR.FD_ORGTYP
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdOrgtyp(String fdOrgtyp) {
        this.fdOrgtyp = fdOrgtyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_ORGINFO_EHR.FD_END_DATE
     *
     * @return the value of TB_SYS_ORGINFO_EHR.FD_END_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public String getFdEndDate() {
        return fdEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_ORGINFO_EHR.FD_END_DATE
     *
     * @param fdEndDate the value for TB_SYS_ORGINFO_EHR.FD_END_DATE
     *
     * @mbggenerated Sat Apr 15 13:42:26 CST 2017
     */
    public void setFdEndDate(String fdEndDate) {
        this.fdEndDate = fdEndDate;
    }
}