package com.work.entity;

import java.math.BigDecimal;

public class TbTalentLibstruct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private String libId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_NAME
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private String libName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_PARENT_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private String libParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_DESC
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private String libDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_LEVEL
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private String libLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TALENT_LIBSTRUCT.LIB_ORDER
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    private BigDecimal libOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_ID
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getLibId() {
        return libId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_ID
     *
     * @param libId the value for TB_TALENT_LIBSTRUCT.LIB_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibId(String libId) {
        this.libId = libId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_NAME
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_NAME
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getLibName() {
        return libName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_NAME
     *
     * @param libName the value for TB_TALENT_LIBSTRUCT.LIB_NAME
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibName(String libName) {
        this.libName = libName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_PARENT_ID
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_PARENT_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getLibParentId() {
        return libParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_PARENT_ID
     *
     * @param libParentId the value for TB_TALENT_LIBSTRUCT.LIB_PARENT_ID
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibParentId(String libParentId) {
        this.libParentId = libParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_DESC
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_DESC
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getLibDesc() {
        return libDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_DESC
     *
     * @param libDesc the value for TB_TALENT_LIBSTRUCT.LIB_DESC
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibDesc(String libDesc) {
        this.libDesc = libDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_LEVEL
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_LEVEL
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getLibLevel() {
        return libLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_LEVEL
     *
     * @param libLevel the value for TB_TALENT_LIBSTRUCT.LIB_LEVEL
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibLevel(String libLevel) {
        this.libLevel = libLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TALENT_LIBSTRUCT.LIB_ORDER
     *
     * @return the value of TB_TALENT_LIBSTRUCT.LIB_ORDER
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public BigDecimal getLibOrder() {
        return libOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TALENT_LIBSTRUCT.LIB_ORDER
     *
     * @param libOrder the value for TB_TALENT_LIBSTRUCT.LIB_ORDER
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setLibOrder(BigDecimal libOrder) {
        this.libOrder = libOrder;
    }
}