package com.work.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TbTalentLibstructExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public TbTalentLibstructExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLibIdIsNull() {
            addCriterion("LIB_ID is null");
            return (Criteria) this;
        }

        public Criteria andLibIdIsNotNull() {
            addCriterion("LIB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLibIdEqualTo(String value) {
            addCriterion("LIB_ID =", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotEqualTo(String value) {
            addCriterion("LIB_ID <>", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdGreaterThan(String value) {
            addCriterion("LIB_ID >", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_ID >=", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLessThan(String value) {
            addCriterion("LIB_ID <", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLessThanOrEqualTo(String value) {
            addCriterion("LIB_ID <=", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLike(String value) {
            addCriterion("LIB_ID like", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotLike(String value) {
            addCriterion("LIB_ID not like", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdIn(List<String> values) {
            addCriterion("LIB_ID in", values, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotIn(List<String> values) {
            addCriterion("LIB_ID not in", values, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdBetween(String value1, String value2) {
            addCriterion("LIB_ID between", value1, value2, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotBetween(String value1, String value2) {
            addCriterion("LIB_ID not between", value1, value2, "libId");
            return (Criteria) this;
        }

        public Criteria andLibNameIsNull() {
            addCriterion("LIB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLibNameIsNotNull() {
            addCriterion("LIB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLibNameEqualTo(String value) {
            addCriterion("LIB_NAME =", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameNotEqualTo(String value) {
            addCriterion("LIB_NAME <>", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameGreaterThan(String value) {
            addCriterion("LIB_NAME >", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_NAME >=", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameLessThan(String value) {
            addCriterion("LIB_NAME <", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameLessThanOrEqualTo(String value) {
            addCriterion("LIB_NAME <=", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameLike(String value) {
            addCriterion("LIB_NAME like", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameNotLike(String value) {
            addCriterion("LIB_NAME not like", value, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameIn(List<String> values) {
            addCriterion("LIB_NAME in", values, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameNotIn(List<String> values) {
            addCriterion("LIB_NAME not in", values, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameBetween(String value1, String value2) {
            addCriterion("LIB_NAME between", value1, value2, "libName");
            return (Criteria) this;
        }

        public Criteria andLibNameNotBetween(String value1, String value2) {
            addCriterion("LIB_NAME not between", value1, value2, "libName");
            return (Criteria) this;
        }

        public Criteria andLibParentIdIsNull() {
            addCriterion("LIB_PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andLibParentIdIsNotNull() {
            addCriterion("LIB_PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLibParentIdEqualTo(String value) {
            addCriterion("LIB_PARENT_ID =", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdNotEqualTo(String value) {
            addCriterion("LIB_PARENT_ID <>", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdGreaterThan(String value) {
            addCriterion("LIB_PARENT_ID >", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_PARENT_ID >=", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdLessThan(String value) {
            addCriterion("LIB_PARENT_ID <", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdLessThanOrEqualTo(String value) {
            addCriterion("LIB_PARENT_ID <=", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdLike(String value) {
            addCriterion("LIB_PARENT_ID like", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdNotLike(String value) {
            addCriterion("LIB_PARENT_ID not like", value, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdIn(List<String> values) {
            addCriterion("LIB_PARENT_ID in", values, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdNotIn(List<String> values) {
            addCriterion("LIB_PARENT_ID not in", values, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdBetween(String value1, String value2) {
            addCriterion("LIB_PARENT_ID between", value1, value2, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibParentIdNotBetween(String value1, String value2) {
            addCriterion("LIB_PARENT_ID not between", value1, value2, "libParentId");
            return (Criteria) this;
        }

        public Criteria andLibDescIsNull() {
            addCriterion("LIB_DESC is null");
            return (Criteria) this;
        }

        public Criteria andLibDescIsNotNull() {
            addCriterion("LIB_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andLibDescEqualTo(String value) {
            addCriterion("LIB_DESC =", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescNotEqualTo(String value) {
            addCriterion("LIB_DESC <>", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescGreaterThan(String value) {
            addCriterion("LIB_DESC >", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_DESC >=", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescLessThan(String value) {
            addCriterion("LIB_DESC <", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescLessThanOrEqualTo(String value) {
            addCriterion("LIB_DESC <=", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescLike(String value) {
            addCriterion("LIB_DESC like", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescNotLike(String value) {
            addCriterion("LIB_DESC not like", value, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescIn(List<String> values) {
            addCriterion("LIB_DESC in", values, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescNotIn(List<String> values) {
            addCriterion("LIB_DESC not in", values, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescBetween(String value1, String value2) {
            addCriterion("LIB_DESC between", value1, value2, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibDescNotBetween(String value1, String value2) {
            addCriterion("LIB_DESC not between", value1, value2, "libDesc");
            return (Criteria) this;
        }

        public Criteria andLibLevelIsNull() {
            addCriterion("LIB_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andLibLevelIsNotNull() {
            addCriterion("LIB_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andLibLevelEqualTo(String value) {
            addCriterion("LIB_LEVEL =", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelNotEqualTo(String value) {
            addCriterion("LIB_LEVEL <>", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelGreaterThan(String value) {
            addCriterion("LIB_LEVEL >", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_LEVEL >=", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelLessThan(String value) {
            addCriterion("LIB_LEVEL <", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelLessThanOrEqualTo(String value) {
            addCriterion("LIB_LEVEL <=", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelLike(String value) {
            addCriterion("LIB_LEVEL like", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelNotLike(String value) {
            addCriterion("LIB_LEVEL not like", value, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelIn(List<String> values) {
            addCriterion("LIB_LEVEL in", values, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelNotIn(List<String> values) {
            addCriterion("LIB_LEVEL not in", values, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelBetween(String value1, String value2) {
            addCriterion("LIB_LEVEL between", value1, value2, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibLevelNotBetween(String value1, String value2) {
            addCriterion("LIB_LEVEL not between", value1, value2, "libLevel");
            return (Criteria) this;
        }

        public Criteria andLibOrderIsNull() {
            addCriterion("LIB_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andLibOrderIsNotNull() {
            addCriterion("LIB_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andLibOrderEqualTo(BigDecimal value) {
            addCriterion("LIB_ORDER =", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderNotEqualTo(BigDecimal value) {
            addCriterion("LIB_ORDER <>", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderGreaterThan(BigDecimal value) {
            addCriterion("LIB_ORDER >", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LIB_ORDER >=", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderLessThan(BigDecimal value) {
            addCriterion("LIB_ORDER <", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LIB_ORDER <=", value, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderIn(List<BigDecimal> values) {
            addCriterion("LIB_ORDER in", values, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderNotIn(List<BigDecimal> values) {
            addCriterion("LIB_ORDER not in", values, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LIB_ORDER between", value1, value2, "libOrder");
            return (Criteria) this;
        }

        public Criteria andLibOrderNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LIB_ORDER not between", value1, value2, "libOrder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 21 16:48:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_LIBSTRUCT
     *
     * @mbggenerated Fri Apr 21 16:48:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}