package com.work.entity;

import java.util.ArrayList;
import java.util.List;

public class TbTalentUserinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public TbTalentUserinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLibIdIsNull() {
            addCriterion("LIB_ID is null");
            return (Criteria) this;
        }

        public Criteria andLibIdIsNotNull() {
            addCriterion("LIB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLibIdEqualTo(String value) {
            addCriterion("LIB_ID =", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotEqualTo(String value) {
            addCriterion("LIB_ID <>", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdGreaterThan(String value) {
            addCriterion("LIB_ID >", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdGreaterThanOrEqualTo(String value) {
            addCriterion("LIB_ID >=", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLessThan(String value) {
            addCriterion("LIB_ID <", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLessThanOrEqualTo(String value) {
            addCriterion("LIB_ID <=", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdLike(String value) {
            addCriterion("LIB_ID like", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotLike(String value) {
            addCriterion("LIB_ID not like", value, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdIn(List<String> values) {
            addCriterion("LIB_ID in", values, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotIn(List<String> values) {
            addCriterion("LIB_ID not in", values, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdBetween(String value1, String value2) {
            addCriterion("LIB_ID between", value1, value2, "libId");
            return (Criteria) this;
        }

        public Criteria andLibIdNotBetween(String value1, String value2) {
            addCriterion("LIB_ID not between", value1, value2, "libId");
            return (Criteria) this;
        }

        public Criteria andEhrIsNull() {
            addCriterion("EHR is null");
            return (Criteria) this;
        }

        public Criteria andEhrIsNotNull() {
            addCriterion("EHR is not null");
            return (Criteria) this;
        }

        public Criteria andEhrEqualTo(String value) {
            addCriterion("EHR =", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrNotEqualTo(String value) {
            addCriterion("EHR <>", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrGreaterThan(String value) {
            addCriterion("EHR >", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrGreaterThanOrEqualTo(String value) {
            addCriterion("EHR >=", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrLessThan(String value) {
            addCriterion("EHR <", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrLessThanOrEqualTo(String value) {
            addCriterion("EHR <=", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrLike(String value) {
            addCriterion("EHR like", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrNotLike(String value) {
            addCriterion("EHR not like", value, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrIn(List<String> values) {
            addCriterion("EHR in", values, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrNotIn(List<String> values) {
            addCriterion("EHR not in", values, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrBetween(String value1, String value2) {
            addCriterion("EHR between", value1, value2, "ehr");
            return (Criteria) this;
        }

        public Criteria andEhrNotBetween(String value1, String value2) {
            addCriterion("EHR not between", value1, value2, "ehr");
            return (Criteria) this;
        }

        public Criteria andTalentDescIsNull() {
            addCriterion("TALENT_DESC is null");
            return (Criteria) this;
        }

        public Criteria andTalentDescIsNotNull() {
            addCriterion("TALENT_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andTalentDescEqualTo(String value) {
            addCriterion("TALENT_DESC =", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescNotEqualTo(String value) {
            addCriterion("TALENT_DESC <>", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescGreaterThan(String value) {
            addCriterion("TALENT_DESC >", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescGreaterThanOrEqualTo(String value) {
            addCriterion("TALENT_DESC >=", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescLessThan(String value) {
            addCriterion("TALENT_DESC <", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescLessThanOrEqualTo(String value) {
            addCriterion("TALENT_DESC <=", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescLike(String value) {
            addCriterion("TALENT_DESC like", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescNotLike(String value) {
            addCriterion("TALENT_DESC not like", value, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescIn(List<String> values) {
            addCriterion("TALENT_DESC in", values, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescNotIn(List<String> values) {
            addCriterion("TALENT_DESC not in", values, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescBetween(String value1, String value2) {
            addCriterion("TALENT_DESC between", value1, value2, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentDescNotBetween(String value1, String value2) {
            addCriterion("TALENT_DESC not between", value1, value2, "talentDesc");
            return (Criteria) this;
        }

        public Criteria andTalentTypeIsNull() {
            addCriterion("TALENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTalentTypeIsNotNull() {
            addCriterion("TALENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTalentTypeEqualTo(String value) {
            addCriterion("TALENT_TYPE =", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeNotEqualTo(String value) {
            addCriterion("TALENT_TYPE <>", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeGreaterThan(String value) {
            addCriterion("TALENT_TYPE >", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TALENT_TYPE >=", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeLessThan(String value) {
            addCriterion("TALENT_TYPE <", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeLessThanOrEqualTo(String value) {
            addCriterion("TALENT_TYPE <=", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeLike(String value) {
            addCriterion("TALENT_TYPE like", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeNotLike(String value) {
            addCriterion("TALENT_TYPE not like", value, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeIn(List<String> values) {
            addCriterion("TALENT_TYPE in", values, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeNotIn(List<String> values) {
            addCriterion("TALENT_TYPE not in", values, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeBetween(String value1, String value2) {
            addCriterion("TALENT_TYPE between", value1, value2, "talentType");
            return (Criteria) this;
        }

        public Criteria andTalentTypeNotBetween(String value1, String value2) {
            addCriterion("TALENT_TYPE not between", value1, value2, "talentType");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdIsNull() {
            addCriterion("TOP_CATEGORY_ID is null");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdIsNotNull() {
            addCriterion("TOP_CATEGORY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdEqualTo(String value) {
            addCriterion("TOP_CATEGORY_ID =", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdNotEqualTo(String value) {
            addCriterion("TOP_CATEGORY_ID <>", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdGreaterThan(String value) {
            addCriterion("TOP_CATEGORY_ID >", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("TOP_CATEGORY_ID >=", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdLessThan(String value) {
            addCriterion("TOP_CATEGORY_ID <", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("TOP_CATEGORY_ID <=", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdLike(String value) {
            addCriterion("TOP_CATEGORY_ID like", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdNotLike(String value) {
            addCriterion("TOP_CATEGORY_ID not like", value, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdIn(List<String> values) {
            addCriterion("TOP_CATEGORY_ID in", values, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdNotIn(List<String> values) {
            addCriterion("TOP_CATEGORY_ID not in", values, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdBetween(String value1, String value2) {
            addCriterion("TOP_CATEGORY_ID between", value1, value2, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andTopCategoryIdNotBetween(String value1, String value2) {
            addCriterion("TOP_CATEGORY_ID not between", value1, value2, "topCategoryId");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameIsNull() {
            addCriterion("OTHER_CATEGORY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameIsNotNull() {
            addCriterion("OTHER_CATEGORY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameEqualTo(String value) {
            addCriterion("OTHER_CATEGORY_NAME =", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameNotEqualTo(String value) {
            addCriterion("OTHER_CATEGORY_NAME <>", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameGreaterThan(String value) {
            addCriterion("OTHER_CATEGORY_NAME >", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_CATEGORY_NAME >=", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameLessThan(String value) {
            addCriterion("OTHER_CATEGORY_NAME <", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("OTHER_CATEGORY_NAME <=", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameLike(String value) {
            addCriterion("OTHER_CATEGORY_NAME like", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameNotLike(String value) {
            addCriterion("OTHER_CATEGORY_NAME not like", value, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameIn(List<String> values) {
            addCriterion("OTHER_CATEGORY_NAME in", values, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameNotIn(List<String> values) {
            addCriterion("OTHER_CATEGORY_NAME not in", values, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameBetween(String value1, String value2) {
            addCriterion("OTHER_CATEGORY_NAME between", value1, value2, "otherCategoryName");
            return (Criteria) this;
        }

        public Criteria andOtherCategoryNameNotBetween(String value1, String value2) {
            addCriterion("OTHER_CATEGORY_NAME not between", value1, value2, "otherCategoryName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 25 10:22:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TALENT_USERINFO
     *
     * @mbggenerated Tue Apr 25 10:22:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}