package com.work.entity;

import java.math.BigDecimal;

public class TSugInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_UUID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_TITLE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_EMPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdEmpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_ORGCDE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdOrgcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_PUB_TIME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdPubTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_SUG_TYPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdSugTypid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_APPRO_ORG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdApproOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_EMP
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderEmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_TMIE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderTmie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private BigDecimal fdLeaderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_EMP_NME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdEmpNme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_EMP_UNINME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdEmpUninme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_TYPENME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdTypenme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_APPRO_ORGNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdApproOrgnme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_EMPNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderEmpnme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_REPLY_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdReplyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_COMMENT_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdCommentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LIKE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_DISS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdDiss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_EMP_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderEmpFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_TMIE_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderTmieFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_STATUS_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private BigDecimal fdLeaderStatusFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_SUG_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdSugStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_SUG_SCOPE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdSugScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_SUG_FLAG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdSugFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_CONTENT
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_APP_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdAppMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SUG_INFO.FD_LEADER_MARK_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    private String fdLeaderMarkFirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_UUID
     *
     * @return the value of TB_SUG_INFO.FD_UUID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdUuid() {
        return fdUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_UUID
     *
     * @param fdUuid the value for TB_SUG_INFO.FD_UUID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdUuid(String fdUuid) {
        this.fdUuid = fdUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_TITLE
     *
     * @return the value of TB_SUG_INFO.FD_TITLE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdTitle() {
        return fdTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_TITLE
     *
     * @param fdTitle the value for TB_SUG_INFO.FD_TITLE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdTitle(String fdTitle) {
        this.fdTitle = fdTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_EMPID
     *
     * @return the value of TB_SUG_INFO.FD_EMPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdEmpid() {
        return fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_EMPID
     *
     * @param fdEmpid the value for TB_SUG_INFO.FD_EMPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdEmpid(String fdEmpid) {
        this.fdEmpid = fdEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_ORGCDE
     *
     * @return the value of TB_SUG_INFO.FD_ORGCDE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdOrgcde() {
        return fdOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_ORGCDE
     *
     * @param fdOrgcde the value for TB_SUG_INFO.FD_ORGCDE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdOrgcde(String fdOrgcde) {
        this.fdOrgcde = fdOrgcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_PUB_TIME
     *
     * @return the value of TB_SUG_INFO.FD_PUB_TIME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdPubTime() {
        return fdPubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_PUB_TIME
     *
     * @param fdPubTime the value for TB_SUG_INFO.FD_PUB_TIME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdPubTime(String fdPubTime) {
        this.fdPubTime = fdPubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_SUG_TYPID
     *
     * @return the value of TB_SUG_INFO.FD_SUG_TYPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdSugTypid() {
        return fdSugTypid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_SUG_TYPID
     *
     * @param fdSugTypid the value for TB_SUG_INFO.FD_SUG_TYPID
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdSugTypid(String fdSugTypid) {
        this.fdSugTypid = fdSugTypid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_APPRO_ORG
     *
     * @return the value of TB_SUG_INFO.FD_APPRO_ORG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdApproOrg() {
        return fdApproOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_APPRO_ORG
     *
     * @param fdApproOrg the value for TB_SUG_INFO.FD_APPRO_ORG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdApproOrg(String fdApproOrg) {
        this.fdApproOrg = fdApproOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_EMP
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_EMP
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderEmp() {
        return fdLeaderEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_EMP
     *
     * @param fdLeaderEmp the value for TB_SUG_INFO.FD_LEADER_EMP
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderEmp(String fdLeaderEmp) {
        this.fdLeaderEmp = fdLeaderEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_TMIE
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_TMIE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderTmie() {
        return fdLeaderTmie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_TMIE
     *
     * @param fdLeaderTmie the value for TB_SUG_INFO.FD_LEADER_TMIE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderTmie(String fdLeaderTmie) {
        this.fdLeaderTmie = fdLeaderTmie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_STATUS
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public BigDecimal getFdLeaderStatus() {
        return fdLeaderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_STATUS
     *
     * @param fdLeaderStatus the value for TB_SUG_INFO.FD_LEADER_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderStatus(BigDecimal fdLeaderStatus) {
        this.fdLeaderStatus = fdLeaderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_EMP_NME
     *
     * @return the value of TB_SUG_INFO.FD_EMP_NME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdEmpNme() {
        return fdEmpNme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_EMP_NME
     *
     * @param fdEmpNme the value for TB_SUG_INFO.FD_EMP_NME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdEmpNme(String fdEmpNme) {
        this.fdEmpNme = fdEmpNme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_EMP_UNINME
     *
     * @return the value of TB_SUG_INFO.FD_EMP_UNINME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdEmpUninme() {
        return fdEmpUninme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_EMP_UNINME
     *
     * @param fdEmpUninme the value for TB_SUG_INFO.FD_EMP_UNINME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdEmpUninme(String fdEmpUninme) {
        this.fdEmpUninme = fdEmpUninme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_TYPENME
     *
     * @return the value of TB_SUG_INFO.FD_TYPENME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdTypenme() {
        return fdTypenme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_TYPENME
     *
     * @param fdTypenme the value for TB_SUG_INFO.FD_TYPENME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdTypenme(String fdTypenme) {
        this.fdTypenme = fdTypenme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_APPRO_ORGNME
     *
     * @return the value of TB_SUG_INFO.FD_APPRO_ORGNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdApproOrgnme() {
        return fdApproOrgnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_APPRO_ORGNME
     *
     * @param fdApproOrgnme the value for TB_SUG_INFO.FD_APPRO_ORGNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdApproOrgnme(String fdApproOrgnme) {
        this.fdApproOrgnme = fdApproOrgnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_EMPNME
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_EMPNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderEmpnme() {
        return fdLeaderEmpnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_EMPNME
     *
     * @param fdLeaderEmpnme the value for TB_SUG_INFO.FD_LEADER_EMPNME
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderEmpnme(String fdLeaderEmpnme) {
        this.fdLeaderEmpnme = fdLeaderEmpnme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_REPLY_STATUS
     *
     * @return the value of TB_SUG_INFO.FD_REPLY_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdReplyStatus() {
        return fdReplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_REPLY_STATUS
     *
     * @param fdReplyStatus the value for TB_SUG_INFO.FD_REPLY_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdReplyStatus(String fdReplyStatus) {
        this.fdReplyStatus = fdReplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_COMMENT_STATUS
     *
     * @return the value of TB_SUG_INFO.FD_COMMENT_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdCommentStatus() {
        return fdCommentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_COMMENT_STATUS
     *
     * @param fdCommentStatus the value for TB_SUG_INFO.FD_COMMENT_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdCommentStatus(String fdCommentStatus) {
        this.fdCommentStatus = fdCommentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LIKE
     *
     * @return the value of TB_SUG_INFO.FD_LIKE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLike() {
        return fdLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LIKE
     *
     * @param fdLike the value for TB_SUG_INFO.FD_LIKE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLike(String fdLike) {
        this.fdLike = fdLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_DISS
     *
     * @return the value of TB_SUG_INFO.FD_DISS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdDiss() {
        return fdDiss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_DISS
     *
     * @param fdDiss the value for TB_SUG_INFO.FD_DISS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdDiss(String fdDiss) {
        this.fdDiss = fdDiss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_EMP_FIRST
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_EMP_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderEmpFirst() {
        return fdLeaderEmpFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_EMP_FIRST
     *
     * @param fdLeaderEmpFirst the value for TB_SUG_INFO.FD_LEADER_EMP_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderEmpFirst(String fdLeaderEmpFirst) {
        this.fdLeaderEmpFirst = fdLeaderEmpFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_TMIE_FIRST
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_TMIE_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderTmieFirst() {
        return fdLeaderTmieFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_TMIE_FIRST
     *
     * @param fdLeaderTmieFirst the value for TB_SUG_INFO.FD_LEADER_TMIE_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderTmieFirst(String fdLeaderTmieFirst) {
        this.fdLeaderTmieFirst = fdLeaderTmieFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_STATUS_FIRST
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_STATUS_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public BigDecimal getFdLeaderStatusFirst() {
        return fdLeaderStatusFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_STATUS_FIRST
     *
     * @param fdLeaderStatusFirst the value for TB_SUG_INFO.FD_LEADER_STATUS_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderStatusFirst(BigDecimal fdLeaderStatusFirst) {
        this.fdLeaderStatusFirst = fdLeaderStatusFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_SUG_STATUS
     *
     * @return the value of TB_SUG_INFO.FD_SUG_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdSugStatus() {
        return fdSugStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_SUG_STATUS
     *
     * @param fdSugStatus the value for TB_SUG_INFO.FD_SUG_STATUS
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdSugStatus(String fdSugStatus) {
        this.fdSugStatus = fdSugStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_SUG_SCOPE
     *
     * @return the value of TB_SUG_INFO.FD_SUG_SCOPE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdSugScope() {
        return fdSugScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_SUG_SCOPE
     *
     * @param fdSugScope the value for TB_SUG_INFO.FD_SUG_SCOPE
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdSugScope(String fdSugScope) {
        this.fdSugScope = fdSugScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_SUG_FLAG
     *
     * @return the value of TB_SUG_INFO.FD_SUG_FLAG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdSugFlag() {
        return fdSugFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_SUG_FLAG
     *
     * @param fdSugFlag the value for TB_SUG_INFO.FD_SUG_FLAG
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdSugFlag(String fdSugFlag) {
        this.fdSugFlag = fdSugFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_CONTENT
     *
     * @return the value of TB_SUG_INFO.FD_CONTENT
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdContent() {
        return fdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_CONTENT
     *
     * @param fdContent the value for TB_SUG_INFO.FD_CONTENT
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdContent(String fdContent) {
        this.fdContent = fdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_MARK
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderMark() {
        return fdLeaderMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_MARK
     *
     * @param fdLeaderMark the value for TB_SUG_INFO.FD_LEADER_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderMark(String fdLeaderMark) {
        this.fdLeaderMark = fdLeaderMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_APP_MARK
     *
     * @return the value of TB_SUG_INFO.FD_APP_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdAppMark() {
        return fdAppMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_APP_MARK
     *
     * @param fdAppMark the value for TB_SUG_INFO.FD_APP_MARK
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdAppMark(String fdAppMark) {
        this.fdAppMark = fdAppMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SUG_INFO.FD_LEADER_MARK_FIRST
     *
     * @return the value of TB_SUG_INFO.FD_LEADER_MARK_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public String getFdLeaderMarkFirst() {
        return fdLeaderMarkFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SUG_INFO.FD_LEADER_MARK_FIRST
     *
     * @param fdLeaderMarkFirst the value for TB_SUG_INFO.FD_LEADER_MARK_FIRST
     *
     * @mbggenerated Tue Aug 28 10:19:46 CST 2018
     */
    public void setFdLeaderMarkFirst(String fdLeaderMarkFirst) {
        this.fdLeaderMarkFirst = fdLeaderMarkFirst;
    }
}