package com.work.entity.dating;

public class TBUserActivityComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY_COMMENT.id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY_COMMENT.user_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY_COMMENT.activity_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY_COMMENT.comment_content
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY_COMMENT.create_time
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY_COMMENT.id
     *
     * @return the value of TB_USER_ACTIVITY_COMMENT.id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY_COMMENT.id
     *
     * @param id the value for TB_USER_ACTIVITY_COMMENT.id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY_COMMENT.user_id
     *
     * @return the value of TB_USER_ACTIVITY_COMMENT.user_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY_COMMENT.user_id
     *
     * @param userId the value for TB_USER_ACTIVITY_COMMENT.user_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY_COMMENT.activity_id
     *
     * @return the value of TB_USER_ACTIVITY_COMMENT.activity_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY_COMMENT.activity_id
     *
     * @param activityId the value for TB_USER_ACTIVITY_COMMENT.activity_id
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY_COMMENT.comment_content
     *
     * @return the value of TB_USER_ACTIVITY_COMMENT.comment_content
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY_COMMENT.comment_content
     *
     * @param commentContent the value for TB_USER_ACTIVITY_COMMENT.comment_content
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY_COMMENT.create_time
     *
     * @return the value of TB_USER_ACTIVITY_COMMENT.create_time
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY_COMMENT.create_time
     *
     * @param createTime the value for TB_USER_ACTIVITY_COMMENT.create_time
     *
     * @mbggenerated Fri May 05 16:20:43 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}