package com.work.entity.dating;

public class TBUserIntermediaryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.USER_ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.SELF_DESCRIPTION
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String selfDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.USER_NAME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_INFO.SUCCESS_RATE
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    private String successRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.ID
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.ID
     *
     * @param id the value for TB_USER_INTERMEDIARY_INFO.ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.USER_ID
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.USER_ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.USER_ID
     *
     * @param userId the value for TB_USER_INTERMEDIARY_INFO.USER_ID
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.SELF_DESCRIPTION
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.SELF_DESCRIPTION
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getSelfDescription() {
        return selfDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.SELF_DESCRIPTION
     *
     * @param selfDescription the value for TB_USER_INTERMEDIARY_INFO.SELF_DESCRIPTION
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setSelfDescription(String selfDescription) {
        this.selfDescription = selfDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.CREATE_TIME
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.CREATE_TIME
     *
     * @param createTime the value for TB_USER_INTERMEDIARY_INFO.CREATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.UPDATE_TIME
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.UPDATE_TIME
     *
     * @param updateTime the value for TB_USER_INTERMEDIARY_INFO.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.USER_NAME
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.USER_NAME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.USER_NAME
     *
     * @param userName the value for TB_USER_INTERMEDIARY_INFO.USER_NAME
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_INFO.SUCCESS_RATE
     *
     * @return the value of TB_USER_INTERMEDIARY_INFO.SUCCESS_RATE
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public String getSuccessRate() {
        return successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_INFO.SUCCESS_RATE
     *
     * @param successRate the value for TB_USER_INTERMEDIARY_INFO.SUCCESS_RATE
     *
     * @mbggenerated Fri Apr 28 12:21:13 CST 2017
     */
    public void setSuccessRate(String successRate) {
        this.successRate = successRate;
    }
}