package com.work.entity.dating;

public class TBUserRecommentSuccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RECOMMENT_SUCCESS.ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RECOMMENT_SUCCESS.DATING_INFO_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    private String datingInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RECOMMENT_SUCCESS.INTERMEDIARY_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    private String intermediaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RECOMMENT_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RECOMMENT_SUCCESS.UPDATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RECOMMENT_SUCCESS.ID
     *
     * @return the value of TB_USER_RECOMMENT_SUCCESS.ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RECOMMENT_SUCCESS.ID
     *
     * @param id the value for TB_USER_RECOMMENT_SUCCESS.ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RECOMMENT_SUCCESS.DATING_INFO_ID
     *
     * @return the value of TB_USER_RECOMMENT_SUCCESS.DATING_INFO_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public String getDatingInfoId() {
        return datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RECOMMENT_SUCCESS.DATING_INFO_ID
     *
     * @param datingInfoId the value for TB_USER_RECOMMENT_SUCCESS.DATING_INFO_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public void setDatingInfoId(String datingInfoId) {
        this.datingInfoId = datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RECOMMENT_SUCCESS.INTERMEDIARY_ID
     *
     * @return the value of TB_USER_RECOMMENT_SUCCESS.INTERMEDIARY_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public String getIntermediaryId() {
        return intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RECOMMENT_SUCCESS.INTERMEDIARY_ID
     *
     * @param intermediaryId the value for TB_USER_RECOMMENT_SUCCESS.INTERMEDIARY_ID
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public void setIntermediaryId(String intermediaryId) {
        this.intermediaryId = intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RECOMMENT_SUCCESS.CREATE_TIME
     *
     * @return the value of TB_USER_RECOMMENT_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RECOMMENT_SUCCESS.CREATE_TIME
     *
     * @param createTime the value for TB_USER_RECOMMENT_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RECOMMENT_SUCCESS.UPDATE_TIME
     *
     * @return the value of TB_USER_RECOMMENT_SUCCESS.UPDATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RECOMMENT_SUCCESS.UPDATE_TIME
     *
     * @param updateTime the value for TB_USER_RECOMMENT_SUCCESS.UPDATE_TIME
     *
     * @mbggenerated Thu May 04 15:24:10 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}