package com.work.entity.dating;

import java.util.ArrayList;
import java.util.List;

public class TBUserRelationActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public TBUserRelationActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdIsNull() {
            addCriterion("DATING_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdIsNotNull() {
            addCriterion("DATING_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdEqualTo(String value) {
            addCriterion("DATING_USER_ID =", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdNotEqualTo(String value) {
            addCriterion("DATING_USER_ID <>", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdGreaterThan(String value) {
            addCriterion("DATING_USER_ID >", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("DATING_USER_ID >=", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdLessThan(String value) {
            addCriterion("DATING_USER_ID <", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdLessThanOrEqualTo(String value) {
            addCriterion("DATING_USER_ID <=", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdLike(String value) {
            addCriterion("DATING_USER_ID like", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdNotLike(String value) {
            addCriterion("DATING_USER_ID not like", value, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdIn(List<String> values) {
            addCriterion("DATING_USER_ID in", values, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdNotIn(List<String> values) {
            addCriterion("DATING_USER_ID not in", values, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdBetween(String value1, String value2) {
            addCriterion("DATING_USER_ID between", value1, value2, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andDatingUserIdNotBetween(String value1, String value2) {
            addCriterion("DATING_USER_ID not between", value1, value2, "datingUserId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("ACTIVITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("ACTIVITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(String value) {
            addCriterion("ACTIVITY_ID =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(String value) {
            addCriterion("ACTIVITY_ID <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(String value) {
            addCriterion("ACTIVITY_ID >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_ID >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(String value) {
            addCriterion("ACTIVITY_ID <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_ID <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLike(String value) {
            addCriterion("ACTIVITY_ID like", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotLike(String value) {
            addCriterion("ACTIVITY_ID not like", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<String> values) {
            addCriterion("ACTIVITY_ID in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<String> values) {
            addCriterion("ACTIVITY_ID not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(String value1, String value2) {
            addCriterion("ACTIVITY_ID between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(String value1, String value2) {
            addCriterion("ACTIVITY_ID not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserCommentsIsNull() {
            addCriterion("USER_COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andUserCommentsIsNotNull() {
            addCriterion("USER_COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andUserCommentsEqualTo(String value) {
            addCriterion("USER_COMMENTS =", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsNotEqualTo(String value) {
            addCriterion("USER_COMMENTS <>", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsGreaterThan(String value) {
            addCriterion("USER_COMMENTS >", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("USER_COMMENTS >=", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsLessThan(String value) {
            addCriterion("USER_COMMENTS <", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsLessThanOrEqualTo(String value) {
            addCriterion("USER_COMMENTS <=", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsLike(String value) {
            addCriterion("USER_COMMENTS like", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsNotLike(String value) {
            addCriterion("USER_COMMENTS not like", value, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsIn(List<String> values) {
            addCriterion("USER_COMMENTS in", values, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsNotIn(List<String> values) {
            addCriterion("USER_COMMENTS not in", values, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsBetween(String value1, String value2) {
            addCriterion("USER_COMMENTS between", value1, value2, "userComments");
            return (Criteria) this;
        }

        public Criteria andUserCommentsNotBetween(String value1, String value2) {
            addCriterion("USER_COMMENTS not between", value1, value2, "userComments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated do_not_delete_during_merge Thu May 04 17:34:59 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER_RELATION_ACTIVITY
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}