package com.work.entity.dating;

public class TBUserActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ACTIVITY_TITLE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ACTIVITY_PLACE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ACTIVITY_STARTDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ACTIVITY_ENDDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.LOGO_URL
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.STATUS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.CREATE_USER_EMPID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String createUserEmpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_ACTIVITY.ACTIVITY_CONTENT
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ID
     *
     * @return the value of TB_USER_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ID
     *
     * @param id the value for TB_USER_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ACTIVITY_TITLE
     *
     * @return the value of TB_USER_ACTIVITY.ACTIVITY_TITLE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ACTIVITY_TITLE
     *
     * @param activityTitle the value for TB_USER_ACTIVITY.ACTIVITY_TITLE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ACTIVITY_PLACE
     *
     * @return the value of TB_USER_ACTIVITY.ACTIVITY_PLACE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityPlace() {
        return activityPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ACTIVITY_PLACE
     *
     * @param activityPlace the value for TB_USER_ACTIVITY.ACTIVITY_PLACE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityPlace(String activityPlace) {
        this.activityPlace = activityPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ACTIVITY_STARTDATE
     *
     * @return the value of TB_USER_ACTIVITY.ACTIVITY_STARTDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityStartdate() {
        return activityStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ACTIVITY_STARTDATE
     *
     * @param activityStartdate the value for TB_USER_ACTIVITY.ACTIVITY_STARTDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityStartdate(String activityStartdate) {
        this.activityStartdate = activityStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ACTIVITY_ENDDATE
     *
     * @return the value of TB_USER_ACTIVITY.ACTIVITY_ENDDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityEnddate() {
        return activityEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ACTIVITY_ENDDATE
     *
     * @param activityEnddate the value for TB_USER_ACTIVITY.ACTIVITY_ENDDATE
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityEnddate(String activityEnddate) {
        this.activityEnddate = activityEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.LOGO_URL
     *
     * @return the value of TB_USER_ACTIVITY.LOGO_URL
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.LOGO_URL
     *
     * @param logoUrl the value for TB_USER_ACTIVITY.LOGO_URL
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.CREATE_TIME
     *
     * @return the value of TB_USER_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.CREATE_TIME
     *
     * @param createTime the value for TB_USER_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.STATUS
     *
     * @return the value of TB_USER_ACTIVITY.STATUS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.STATUS
     *
     * @param status the value for TB_USER_ACTIVITY.STATUS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.CREATE_USER_EMPID
     *
     * @return the value of TB_USER_ACTIVITY.CREATE_USER_EMPID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getCreateUserEmpid() {
        return createUserEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.CREATE_USER_EMPID
     *
     * @param createUserEmpid the value for TB_USER_ACTIVITY.CREATE_USER_EMPID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setCreateUserEmpid(String createUserEmpid) {
        this.createUserEmpid = createUserEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_ACTIVITY.ACTIVITY_CONTENT
     *
     * @return the value of TB_USER_ACTIVITY.ACTIVITY_CONTENT
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_ACTIVITY.ACTIVITY_CONTENT
     *
     * @param activityContent the value for TB_USER_ACTIVITY.ACTIVITY_CONTENT
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent;
    }
}