package com.work.entity.dating;

public class TBUserIntermediaryRecommend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.DATING_INFO_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String datingInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.INTERMEDIARY_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String intermediaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.CREATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.UPDATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.RECOMMEND_USER_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String recommendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_INTERMEDIARY_RECOMMEND.TABLE_FLAG
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    private String tableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.ID
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.ID
     *
     * @param id the value for TB_USER_INTERMEDIARY_RECOMMEND.ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.DATING_INFO_ID
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.DATING_INFO_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getDatingInfoId() {
        return datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.DATING_INFO_ID
     *
     * @param datingInfoId the value for TB_USER_INTERMEDIARY_RECOMMEND.DATING_INFO_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setDatingInfoId(String datingInfoId) {
        this.datingInfoId = datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.INTERMEDIARY_ID
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.INTERMEDIARY_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getIntermediaryId() {
        return intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.INTERMEDIARY_ID
     *
     * @param intermediaryId the value for TB_USER_INTERMEDIARY_RECOMMEND.INTERMEDIARY_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setIntermediaryId(String intermediaryId) {
        this.intermediaryId = intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.CREATE_TIME
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.CREATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.CREATE_TIME
     *
     * @param createTime the value for TB_USER_INTERMEDIARY_RECOMMEND.CREATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.UPDATE_TIME
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.UPDATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.UPDATE_TIME
     *
     * @param updateTime the value for TB_USER_INTERMEDIARY_RECOMMEND.UPDATE_TIME
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.RECOMMEND_USER_ID
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.RECOMMEND_USER_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getRecommendUserId() {
        return recommendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.RECOMMEND_USER_ID
     *
     * @param recommendUserId the value for TB_USER_INTERMEDIARY_RECOMMEND.RECOMMEND_USER_ID
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setRecommendUserId(String recommendUserId) {
        this.recommendUserId = recommendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.TABLE_FLAG
     *
     * @return the value of TB_USER_INTERMEDIARY_RECOMMEND.TABLE_FLAG
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public String getTableFlag() {
        return tableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_INTERMEDIARY_RECOMMEND.TABLE_FLAG
     *
     * @param tableFlag the value for TB_USER_INTERMEDIARY_RECOMMEND.TABLE_FLAG
     *
     * @mbggenerated Fri May 19 09:19:37 CST 2017
     */
    public void setTableFlag(String tableFlag) {
        this.tableFlag = tableFlag;
    }
}