package com.work.entity.dating;

public class TBUserRelationActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_ACTIVITY.DATING_USER_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String datingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_ACTIVITY.USER_COMMENTS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    private String userComments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_ACTIVITY.ID
     *
     * @return the value of TB_USER_RELATION_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_ACTIVITY.ID
     *
     * @param id the value for TB_USER_RELATION_ACTIVITY.ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_ACTIVITY.DATING_USER_ID
     *
     * @return the value of TB_USER_RELATION_ACTIVITY.DATING_USER_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getDatingUserId() {
        return datingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_ACTIVITY.DATING_USER_ID
     *
     * @param datingUserId the value for TB_USER_RELATION_ACTIVITY.DATING_USER_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setDatingUserId(String datingUserId) {
        this.datingUserId = datingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_ACTIVITY.ACTIVITY_ID
     *
     * @return the value of TB_USER_RELATION_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_ACTIVITY.ACTIVITY_ID
     *
     * @param activityId the value for TB_USER_RELATION_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_ACTIVITY.CREATE_TIME
     *
     * @return the value of TB_USER_RELATION_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_ACTIVITY.CREATE_TIME
     *
     * @param createTime the value for TB_USER_RELATION_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_ACTIVITY.USER_COMMENTS
     *
     * @return the value of TB_USER_RELATION_ACTIVITY.USER_COMMENTS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public String getUserComments() {
        return userComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_ACTIVITY.USER_COMMENTS
     *
     * @param userComments the value for TB_USER_RELATION_ACTIVITY.USER_COMMENTS
     *
     * @mbggenerated Thu May 04 17:34:59 CST 2017
     */
    public void setUserComments(String userComments) {
        this.userComments = userComments;
    }
}