package com.work.entity.dating;

public class TBUserRelationIntermediay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.DATING_INFO_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String datingInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.INTERMEDIACRY_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String intermediacryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.CREATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_RELATION_INTERMEDIARY.STATUS
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.ID
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.ID
     *
     * @param id the value for TB_USER_RELATION_INTERMEDIARY.ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.DATING_INFO_ID
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.DATING_INFO_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getDatingInfoId() {
        return datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.DATING_INFO_ID
     *
     * @param datingInfoId the value for TB_USER_RELATION_INTERMEDIARY.DATING_INFO_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setDatingInfoId(String datingInfoId) {
        this.datingInfoId = datingInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.INTERMEDIACRY_ID
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.INTERMEDIACRY_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getIntermediacryId() {
        return intermediacryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.INTERMEDIACRY_ID
     *
     * @param intermediacryId the value for TB_USER_RELATION_INTERMEDIARY.INTERMEDIACRY_ID
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setIntermediacryId(String intermediacryId) {
        this.intermediacryId = intermediacryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.CREATE_TIME
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.CREATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.CREATE_TIME
     *
     * @param createTime the value for TB_USER_RELATION_INTERMEDIARY.CREATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.UPDATE_TIME
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.UPDATE_TIME
     *
     * @param updateTime the value for TB_USER_RELATION_INTERMEDIARY.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_RELATION_INTERMEDIARY.STATUS
     *
     * @return the value of TB_USER_RELATION_INTERMEDIARY.STATUS
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_RELATION_INTERMEDIARY.STATUS
     *
     * @param status the value for TB_USER_RELATION_INTERMEDIARY.STATUS
     *
     * @mbggenerated Tue May 02 14:50:54 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}