package com.work.entity.dating;

public class TbUserDatingPublic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.P_KEY
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String pKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.P_VALUE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String pValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.CREATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.RECORD_ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER_DATING_PUBLIC.RECORD_TYPE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    private String recordType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.ID
     *
     * @return the value of TB_USER_DATING_PUBLIC.ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.ID
     *
     * @param id the value for TB_USER_DATING_PUBLIC.ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.P_KEY
     *
     * @return the value of TB_USER_DATING_PUBLIC.P_KEY
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.P_KEY
     *
     * @param pKey the value for TB_USER_DATING_PUBLIC.P_KEY
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setpKey(String pKey) {
        this.pKey = pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.P_VALUE
     *
     * @return the value of TB_USER_DATING_PUBLIC.P_VALUE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.P_VALUE
     *
     * @param pValue the value for TB_USER_DATING_PUBLIC.P_VALUE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setpValue(String pValue) {
        this.pValue = pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.CREATE_TIME
     *
     * @return the value of TB_USER_DATING_PUBLIC.CREATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.CREATE_TIME
     *
     * @param createTime the value for TB_USER_DATING_PUBLIC.CREATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.UPDATE_TIME
     *
     * @return the value of TB_USER_DATING_PUBLIC.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.UPDATE_TIME
     *
     * @param updateTime the value for TB_USER_DATING_PUBLIC.UPDATE_TIME
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.RECORD_ID
     *
     * @return the value of TB_USER_DATING_PUBLIC.RECORD_ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.RECORD_ID
     *
     * @param recordId the value for TB_USER_DATING_PUBLIC.RECORD_ID
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER_DATING_PUBLIC.RECORD_TYPE
     *
     * @return the value of TB_USER_DATING_PUBLIC.RECORD_TYPE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER_DATING_PUBLIC.RECORD_TYPE
     *
     * @param recordType the value for TB_USER_DATING_PUBLIC.RECORD_TYPE
     *
     * @mbggenerated Tue May 02 17:05:11 CST 2017
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType;
    }
}